# 4_0 — Unified Pipeline (Load → Fill Missing → Plot)

Single notebook that:

1. **Loads** every result from `master_db.json` (creates it if missing).
2. **Detects** missing pieces: baseline metrics, SSL summaries, TFT threshold sweeps, per-class breakdowns.
3. **Fills** missing pieces by running only the needed evaluation (no retraining).
4. **Saves** the updated DB back.
5. **Plots** every figure from the DB, into `final_plot/`.

All outputs are deterministic. Re-runs only recompute what is missing; add `FORCE_RECOMPUTE` flags to override.

In [1]:
# =====================================================================
# Cell 1 — Imports + device + config
# =====================================================================
import os, gc, json, glob, math, pickle, contextlib, warnings, datetime
from collections import Counter, defaultdict
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torch_geometric.data import Batch
from torch_geometric.loader import DataLoader as PyGLoader
from torch_geometric.nn import (GATConv, GlobalAttention, GCNConv, GATv2Conv,
                                SAGEConv, MessagePassing, global_mean_pool)
from sklearn.metrics import (roc_curve, precision_recall_curve,
                             confusion_matrix, f1_score,
                             roc_auc_score, average_precision_score)
from sklearn.preprocessing import StandardScaler
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from scipy.sparse import coo_matrix
from scipy.sparse.csgraph import connected_components
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from IPython.display import display, Markdown

warnings.filterwarnings('ignore')
sns.set_theme(context='paper', style='whitegrid', palette='deep')
plt.rcParams.update({'figure.dpi': 120, 'savefig.dpi': 300,
                     'font.size': 10, 'axes.titlesize': 11})

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device: {DEVICE}')

Device: cuda

In [2]:
# =====================================================================
# Cell 2 — Global config
# =====================================================================
DATASET_CONFIG = {
    'gotham': 'Gotham_processed_features_10s/graphs',
    'nf_bot': 'NFBoTIoT_v3_10s/graphs',
    'nf_ton': 'NFToNIoT_v3_10s/graphs',
}
DATASET_ORDER         = ['gotham', 'nf_bot', 'nf_ton']
BASELINE_CKPT_DIR     = 'baseline_checkpoints_tftparity'
BASELINE_JSON         = os.path.join(BASELINE_CKPT_DIR, 'baseline_benchmark.json')
BASELINE_METHOD_ORDER = ['mlp', 'gcn', 'gat', 'sage', 'egs', 'anomal_e']
SSL_ORDER             = ['byol', 'moco']
TFT_MODE_ORDER        = ['frozen_single', 'finetune_single',
                         'frozen_ensemble', 'finetune_ensemble']
SSL_JSONS = {
    'byol': 'pure_byol_ssl_summary.json',
    'moco': 'pure_moco_ssl_summary.json',
}

# Architecture
HIDDEN_DIM      = 128
NUM_HEADS       = 4
NUM_LAYERS      = 3
TFT_HIDDEN_DIM  = 384
TFT_NUM_HEADS   = 2
TFT_DROPOUT     = 0.10
SEQUENCE_LENGTH = 10
SEQUENCE_STRIDE = 1
EVAL_BATCH_SIZE = 32
MAX_NODES       = 128
MAX_EDGES_PER_DATASET = {'gotham': 2000, 'nf_ton': 10000, 'nf_bot': 15000}
DATASET_THRESHOLDS    = {'gotham': 0, 'nf_ton': 0, 'nf_bot': 0}
ATTACK_THR_DEFAULT    = 0.10
WINDOW_SEC            = 10

# Behaviour flags
FORCE_RECOMPUTE_BASELINE = False
FORCE_RECOMPUTE_SSL      = False
FORCE_RECOMPUTE_TFT      = False
FORCE_RECOMPUTE_ALL      = False

# DB + output paths
MASTER_DB      = 'master_db.json'
FINAL_ROOT     = 'final_plot'
DIR_FIGS       = os.path.join(FINAL_ROOT, 'figures')
DIR_SPLIT      = os.path.join(FINAL_ROOT, 'split_plots')
DIR_SSL_BYOL   = os.path.join(FINAL_ROOT, 'ssl_plots', 'BYOL')
DIR_SSL_MOCO   = os.path.join(FINAL_ROOT, 'ssl_plots', 'MOCO')
DIR_BASELINE   = os.path.join(FINAL_ROOT, 'baseline_plots', 'Baseline')
DIR_TFT_BYOL   = os.path.join(FINAL_ROOT, 'phase3_plots')
DIR_TFT_MOCO   = os.path.join(FINAL_ROOT, 'phase3_plots_moco')
for d in (DIR_FIGS, DIR_SPLIT, DIR_SSL_BYOL, DIR_SSL_MOCO,
          DIR_BASELINE, DIR_TFT_BYOL, DIR_TFT_MOCO):
    os.makedirs(d, exist_ok=True)

# =====================================================================
# Helpers
# =====================================================================
_saved = {'ok': 0, 'fail': 0}

def save_fig(fig, path, show=False):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    try:
        fig.tight_layout()
        fig.savefig(path, dpi=140, bbox_inches='tight')
        if show: plt.show()
        plt.close(fig)
        print(f'  [plot] {path}')
        _saved['ok'] += 1
    except Exception as e:
        plt.close(fig)
        print(f'  [FAIL] {path}: {e}')
        _saved['fail'] += 1

def safe_section(name):
    return _SafeSection(name)

class _SafeSection:
    def __init__(self, name): self.name = name
    def __enter__(self):
        print(f"\n{'='*80}\n  {self.name}\n{'='*80}"); return self
    def __exit__(self, t, v, tb):
        if t is not None:
            import traceback
            print(f"  [SECTION FAIL] {self.name}: {v}")
            traceback.print_exc()
            return True
        return False

def slug(s): return s.replace(' ', '_').replace('/', '_')

def load_json(path):
    if not os.path.isfile(path): return None
    try:
        with open(path) as f: return json.load(f)
    except Exception: return None

def load_pickle(path):
    if not os.path.isfile(path): return None
    with open(path, 'rb') as f: return pickle.load(f)

def save_json(path, obj):
    tmp = path + '.tmp'
    with open(tmp, 'w') as f:
        json.dump(obj, f, indent=2, default=float)
    os.replace(tmp, path)

print('Config + helpers ready.')
for ds in DATASET_ORDER:
    d = DATASET_CONFIG[ds]
    print(f'  {ds:<8}  {"OK" if os.path.isdir(d) else "MISSING"}  {d}')

Config + helpers ready.
  gotham    OK  Gotham_processed_features_10s/graphs
  nf_bot    OK  NFBoTIoT_v3_10s/graphs
  nf_ton    OK  NFToNIoT_v3_10s/graphs

In [3]:
# =====================================================================
# Cell 3 — Model classes (GAT encoder + TFT + baseline models)
# =====================================================================

class GATEncoder(nn.Module):
    def __init__(self, in_ch, hid, heads, layers, edge_dim):
        super().__init__()
        self.convs = nn.ModuleList(); self.bns = nn.ModuleList()
        self.convs.append(GATConv(in_ch, hid, heads=heads, edge_dim=edge_dim,
                                  concat=True, dropout=0.0))
        self.bns.append(nn.BatchNorm1d(hid * heads))
        for _ in range(layers - 2):
            self.convs.append(GATConv(hid*heads, hid, heads=heads,
                                      edge_dim=edge_dim, concat=True, dropout=0.0))
            self.bns.append(nn.BatchNorm1d(hid * heads))
        self.convs.append(GATConv(hid*heads, hid, heads=1, edge_dim=edge_dim,
                                  concat=False, dropout=0.0))
        self.bns.append(nn.BatchNorm1d(hid))
        self.edge_dim = edge_dim
        self.pool_gate = nn.Sequential(nn.Linear(hid, hid), nn.ReLU(), nn.Linear(hid, 1))
    def forward(self, x, ei, ea=None, b=None, return_nodes=False):
        for i, c in enumerate(self.convs):
            x = c(x, ei, edge_attr=ea) if (ea is not None and self.edge_dim > 0) else c(x, ei)
            x = F.relu(self.bns[i](x))
        h = GlobalAttention(self.pool_gate)(x, b)
        return (x, h) if return_nodes else h

class GatedResidualNetwork(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim, dropout=0.1):
        super().__init__()
        self.fc1  = nn.Linear(input_dim, hidden_dim); self.elu = nn.ELU()
        self.fc2  = nn.Linear(hidden_dim, output_dim); self.drop = nn.Dropout(dropout)
        self.gate = nn.Linear(hidden_dim, output_dim); self.norm = nn.LayerNorm(output_dim)
        self.skip = nn.Linear(input_dim, output_dim) if input_dim != output_dim else None
    def forward(self, x):
        z = self.elu(self.fc1(x)); h = self.drop(self.fc2(z))
        g = torch.sigmoid(self.gate(z)); h = g * h
        if self.skip is not None: x = self.skip(x)
        return self.norm(x + h)

class VariableSelectionNetwork(nn.Module):
    def __init__(self, var_dims, hidden_dim, dropout=0.1):
        super().__init__()
        self.num_vars = len(var_dims)
        self.var_grns = nn.ModuleList(
            [GatedResidualNetwork(d, hidden_dim, hidden_dim, dropout) for d in var_dims])
        self.weight_grn = GatedResidualNetwork(sum(var_dims), hidden_dim, self.num_vars, dropout)
    def forward(self, vars_list):
        processed = [grn(v) for grn, v in zip(self.var_grns, vars_list)]
        flat = torch.cat(vars_list, dim=-1)
        w = F.softmax(self.weight_grn(flat), dim=-1)
        stacked = torch.stack(processed, dim=2)
        return (stacked * w.unsqueeze(-1)).sum(dim=2), w

class InterpretableMHA(nn.Module):
    def __init__(self, hidden_dim, num_heads, dropout=0.1, init_temp=0.05):
        super().__init__()
        self.h = hidden_dim; self.nh = num_heads; self.hd = hidden_dim // num_heads
        assert self.hd * num_heads == hidden_dim
        self.q = nn.Linear(hidden_dim, hidden_dim)
        self.k = nn.Linear(hidden_dim, hidden_dim)
        self.v = nn.Linear(hidden_dim, hidden_dim)
        self.o = nn.Linear(hidden_dim, hidden_dim)
        self.drop = nn.Dropout(dropout)
        self.register_buffer('log_temp', torch.tensor(float(np.log(init_temp))))
        self.min_temp = 0.05; self.max_temp = 100.0
    def forward_last(self, x):
        B, T, _ = x.shape
        q_last = self.q(x[:, -1:, :]).view(B, 1, self.nh, self.hd).transpose(1, 2)
        k_all  = self.k(x).view(B, T, self.nh, self.hd).transpose(1, 2)
        v_all  = self.v(x).view(B, T, self.nh, self.hd).transpose(1, 2)
        temp   = torch.exp(self.log_temp).clamp(self.min_temp, self.max_temp)
        scale  = 1.0 / ((self.hd ** 0.5) * temp)
        s = torch.matmul(q_last, k_all.transpose(-2, -1)) * scale
        s = torch.nan_to_num(s, nan=-1e4, posinf=1e4, neginf=-1e4)
        s = s - s.amax(dim=-1, keepdim=True).detach()
        s = torch.nan_to_num(s, nan=0.0, posinf=0.0, neginf=-1e4)
        a = self.drop(F.softmax(s, dim=-1))
        c = torch.matmul(a, v_all).transpose(1, 2).contiguous().view(B, 1, self.h)
        return self.o(c).squeeze(1), a.squeeze(2).mean(dim=1)

class TemporalFusionModuleV2(nn.Module):
    def __init__(self, graph_emb_dim, struct_dim, hidden_dim, num_heads, dropout=0.1):
        super().__init__()
        self.proj_graph  = nn.Linear(graph_emb_dim, hidden_dim)
        self.proj_struct = nn.Linear(struct_dim, hidden_dim)
        self.vsn  = VariableSelectionNetwork([hidden_dim, hidden_dim], hidden_dim, dropout)
        self.lstm = nn.LSTM(hidden_dim, hidden_dim, num_layers=2, batch_first=True, dropout=dropout)
        self.attn = InterpretableMHA(hidden_dim, num_heads, dropout)
        self.grn1 = GatedResidualNetwork(hidden_dim, hidden_dim, hidden_dim, dropout)
        self.grn2 = GatedResidualNetwork(hidden_dim, hidden_dim, hidden_dim, dropout)
        self.norm = nn.LayerNorm(hidden_dim)
    def forward(self, graph_emb, struct_feats):
        v_g = self.proj_graph(graph_emb); v_s = self.proj_struct(struct_feats)
        selected, vsn_w = self.vsn([v_g, v_s])
        lstm_out, _ = self.lstm(selected)
        attn_last, attn_w = self.attn.forward_last(lstm_out)
        out = self.grn1(attn_last); out = self.grn2(out)
        out = self.norm(selected[:, -1, :] + out)
        return out, attn_w, vsn_w

class MC_STGAT_IDS(nn.Module):
    def __init__(self, graph_emb_dim, struct_dim, tft_hidden, num_classes,
                 num_heads=4, dropout=0.1):
        super().__init__()
        self.temporal = TemporalFusionModuleV2(graph_emb_dim, struct_dim,
                                               tft_hidden, num_heads, dropout)
        self.binary_head = nn.Sequential(
            nn.Linear(tft_hidden, tft_hidden // 2), nn.ReLU(),
            nn.Dropout(dropout), nn.Linear(tft_hidden // 2, 1))
        self.multi_head = nn.Sequential(
            nn.Linear(tft_hidden, tft_hidden // 2), nn.ReLU(),
            nn.Dropout(dropout), nn.Linear(tft_hidden // 2, num_classes))
    def forward(self, graph_emb, struct_feats):
        temporal_emb, attn_w, vsn_w = self.temporal(graph_emb, struct_feats)
        return (self.binary_head(temporal_emb).squeeze(-1),
                self.multi_head(temporal_emb), attn_w, vsn_w)

class GraphMLP(nn.Module):
    def __init__(self, node_dim, edge_dim, hidden=128, num_layers=2,
                 num_classes=2, dropout=0.3):
        super().__init__()
        self.edge_dim = edge_dim
        self.classifier = nn.Sequential(
            nn.Linear(node_dim + edge_dim, hidden), nn.ReLU(), nn.Dropout(dropout),
            nn.Linear(hidden, hidden),               nn.ReLU(), nn.Dropout(dropout),
            nn.Linear(hidden, num_classes))
    def forward(self, batch):
        x, ei, ea, b = batch.x, batch.edge_index, batch.edge_attr, batch.batch
        g_node = global_mean_pool(x, b)
        if ei.size(1) > 0: g_edge = global_mean_pool(ea, b[ei[0]])
        else: g_edge = g_node.new_zeros(g_node.size(0), self.edge_dim)
        return self.classifier(torch.cat([g_node, g_edge], dim=-1))

class GraphClassifier(nn.Module):
    def __init__(self, node_dim, edge_dim, hidden=128, num_layers=3,
                 num_classes=2, conv_type='gcn', dropout=0.3, heads=4):
        super().__init__()
        self.conv_type = conv_type; self.edge_dim = edge_dim
        self.convs = nn.ModuleList(); self.norms = nn.ModuleList()
        for i in range(num_layers):
            d_in = node_dim if i == 0 else hidden
            if conv_type == 'gcn': self.convs.append(GCNConv(d_in, hidden))
            elif conv_type == 'gat':
                self.convs.append(GATv2Conv(d_in, hidden // heads, heads=heads,
                                             edge_dim=edge_dim, concat=True))
            else: self.convs.append(SAGEConv(d_in, hidden))
            self.norms.append(nn.BatchNorm1d(hidden))
        if conv_type == 'sage': self.edge_proj = nn.Linear(edge_dim, hidden)
        self.dropout = dropout
        self.classifier = nn.Sequential(
            nn.Linear(hidden + edge_dim, hidden), nn.ReLU(), nn.Dropout(dropout),
            nn.Linear(hidden, hidden),            nn.ReLU(), nn.Dropout(dropout),
            nn.Linear(hidden, num_classes))
    def _inject_edge_context(self, h, ei, ea):
        if ei.size(1) == 0: return h
        ea_proj = self.edge_proj(ea)
        agg = h.new_zeros(h.size(0), h.size(1))
        agg.index_add_(0, ei[1], ea_proj)
        deg = h.new_zeros(h.size(0), 1).index_add_(
            0, ei[1], torch.ones_like(ei[1], dtype=h.dtype).unsqueeze(-1))
        return h + agg / deg.clamp(min=1.0)
    def encode(self, x, ei, ea, b):
        h = x
        for conv, norm in zip(self.convs, self.norms):
            if self.conv_type == 'gcn': h = conv(h, ei)
            elif self.conv_type == 'gat': h = conv(h, ei, edge_attr=ea)
            else:
                h = conv(h, ei); h = self._inject_edge_context(h, ei, ea)
            h = F.dropout(F.relu(norm(h)), p=self.dropout, training=self.training)
        return h
    def forward(self, batch):
        x, ei, ea, b = batch.x, batch.edge_index, batch.edge_attr, batch.batch
        h = self.encode(x, ei, ea, b)
        g_node = global_mean_pool(h, b)
        if ei.size(1) > 0: g_edge = global_mean_pool(ea, b[ei[0]])
        else: g_edge = g_node.new_zeros(g_node.size(0), self.edge_dim)
        return self.classifier(torch.cat([g_node, g_edge], dim=-1))

class EGraphSAGELayer(MessagePassing):
    def __init__(self, in_node, in_edge, out_dim):
        super().__init__(aggr='mean')
        self.in_edge = in_edge
        self.W_edge = nn.Linear(in_node + in_edge, out_dim, bias=False)
        self.W_self = nn.Linear(in_node + out_dim, out_dim)
    def forward(self, x, edge_index, edge_attr):
        if edge_attr is None or edge_attr.size(-1) == 0:
            edge_attr = x.new_zeros(edge_index.size(1), self.in_edge)
        agg = self.propagate(edge_index, x=x, edge_attr=edge_attr)
        return F.relu(self.W_self(torch.cat([x, agg], dim=-1)))
    def message(self, x_j, edge_attr):
        return self.W_edge(torch.cat([x_j, edge_attr], dim=-1))

class EGraphSAGEClassifier(nn.Module):
    def __init__(self, node_dim, edge_dim, hidden=128, num_layers=3,
                 num_classes=2, dropout=0.3):
        super().__init__()
        self.edge_dim = edge_dim
        self.layers = nn.ModuleList(); self.norms = nn.ModuleList()
        for i in range(num_layers):
            d_in = node_dim if i == 0 else hidden
            self.layers.append(EGraphSAGELayer(d_in, edge_dim, hidden))
            self.norms.append(nn.BatchNorm1d(hidden))
        self.dropout = dropout
        self.classifier = nn.Sequential(
            nn.Linear(hidden + edge_dim, hidden), nn.ReLU(), nn.Dropout(dropout),
            nn.Linear(hidden, hidden),            nn.ReLU(), nn.Dropout(dropout),
            nn.Linear(hidden, num_classes))
    def encode(self, x, ei, ea, b):
        h = x
        for layer, norm in zip(self.layers, self.norms):
            h = layer(h, ei, ea)
            h = F.dropout(F.relu(norm(h)), p=self.dropout, training=self.training)
        return h
    def forward(self, batch):
        x, ei, ea, b = batch.x, batch.edge_index, batch.edge_attr, batch.batch
        h = self.encode(x, ei, ea, b)
        g_node = global_mean_pool(h, b)
        if ei.size(1) > 0: g_edge = global_mean_pool(ea, b[ei[0]])
        else: g_edge = g_node.new_zeros(g_node.size(0), self.edge_dim)
        return self.classifier(torch.cat([g_node, g_edge], dim=-1))

def build_baseline_model(name, node_dim, edge_dim, n_classes, hidden=128, dropout=0.3):
    if name == 'mlp': return GraphMLP(node_dim, edge_dim, hidden, 2, n_classes, dropout)
    if name in ('egs', 'anomal_e'):
        return EGraphSAGEClassifier(node_dim, edge_dim, hidden, 3, n_classes, dropout)
    return GraphClassifier(node_dim, edge_dim, hidden, 3, n_classes, conv_type=name, dropout=dropout)

print('Model classes ready.')

Model classes ready.

In [4]:
# =====================================================================
# Cell 4 — Graph + sequence utilities
# =====================================================================

def cap_graph(g, max_nodes=MAX_NODES, max_edges=None):
    if max_edges is None: max_edges = 20000
    g = g.clone(); num_nodes = g.num_nodes
    if g.edge_index.size(1) > max_edges:
        keep = torch.randperm(g.edge_index.size(1))[:max_edges]
        g.edge_index = g.edge_index[:, keep]
        if g.edge_attr is not None and g.edge_attr.size(0) > 0:
            if g.edge_attr.dim() > 2:
                g.edge_attr = g.edge_attr.view(-1, g.edge_attr.size(-1))
            g.edge_attr = g.edge_attr[keep]
    if num_nodes > max_nodes:
        deg = torch.zeros(num_nodes, dtype=torch.long)
        deg.scatter_add_(0, g.edge_index[0],
                         torch.ones(g.edge_index.size(1), dtype=torch.long))
        kn = torch.topk(deg, max_nodes).indices
        mask = torch.zeros(num_nodes, dtype=torch.bool); mask[kn] = True
        s, d = g.edge_index; keep_e = mask[s] & mask[d]
        g.edge_index = g.edge_index[:, keep_e]
        if g.edge_attr is not None and g.edge_attr.size(0) > 0:
            g.edge_attr = g.edge_attr[keep_e]
        remap = torch.zeros(num_nodes, dtype=torch.long)
        remap[mask] = torch.arange(max_nodes, dtype=torch.long)
        g.edge_index = remap[g.edge_index]; g.x = g.x[mask]
    return g

def dominant_family(g, attack_threshold=0.0,
                    blacklist=('Unknown','unknown','UNKNOWN')):
    names = getattr(g, 'edge_attack_names', None)
    if not names: return 'Benign'
    c = Counter(names); total = sum(c.values())
    atk = {k: v for k, v in c.items() if k != 'Benign' and k not in blacklist}
    if not atk: return 'Benign'
    if sum(atk.values()) / max(total, 1) < attack_threshold: return 'Benign'
    return max(atk, key=atk.get)

def build_gap_aware_starts(graphs, seq_len, stride, max_gap_sec, enforce=True):
    n = len(graphs)
    if n < seq_len: return np.array([], dtype=np.int64)
    stride_only = np.arange(0, n - seq_len + 1, stride, dtype=np.int64)
    if not enforce: return stride_only
    if not hasattr(graphs[0], 'window_start_unix'): return stride_only
    times = np.array([float(g.window_start_unix) for g in graphs], dtype=np.float64)
    gaps = np.diff(times)
    ok = (gaps <= float(max_gap_sec)).astype(np.int32)
    cum = np.concatenate([[0], np.cumsum(ok)])
    keep = (cum[stride_only + seq_len - 1] - cum[stride_only]) == (seq_len - 1)
    kept = stride_only[keep]
    if len(kept) < 10 and len(stride_only) >= 10: return stride_only
    return kept

def structural_features(g):
    x  = g.x.numpy()
    ea = g.edge_attr.numpy() if g.edge_attr is not None else np.zeros((0, 0))
    ei = g.edge_index.numpy()
    N = x.shape[0]; E = ei.shape[1]
    deg = np.bincount(ei[0], minlength=N) if E > 0 else np.zeros(N)
    base = np.array([float(N), float(E),
                     float(deg.mean()) if N > 0 else 0.0,
                     float(np.log1p(E))], dtype=np.float32)
    nm = x.mean(0) if N > 0 else np.zeros(x.shape[1], dtype=np.float32)
    ns = x.std(0)  if N > 0 else np.zeros(x.shape[1], dtype=np.float32)
    em = ea.mean(0) if E > 0 and ea.ndim == 2 else np.zeros(
        ea.shape[-1] if ea.ndim == 2 else 0, dtype=np.float32)
    return np.concatenate([base, nm, ns, em]).astype(np.float32)

def precompute_struct(graphs):
    return torch.tensor(np.stack([structural_features(g) for g in graphs]),
                        dtype=torch.float32)

class GraphSequenceDataset(Dataset):
    def __init__(self, graphs, starts, seq_len, y_bin_seq, y_multi_seq, struct_feats):
        self.graphs = graphs; self.starts = np.asarray(starts); self.seq_len = seq_len
        self.y_bin_seq = y_bin_seq; self.y_multi_seq = y_multi_seq; self.struct = struct_feats
    def __len__(self): return len(self.starts)
    def __getitem__(self, i):
        s = int(self.starts[i]); e = s + self.seq_len
        return (self.graphs[s:e], self.struct[s:e],
                self.y_bin_seq[i], self.y_multi_seq[i])

def collate_graph_sequences(batch):
    seq_graphs_list, seq_struct_list, y_bin_list, y_multi_list = zip(*batch)
    B = len(seq_graphs_list); T = len(seq_graphs_list[0])
    flat_graphs = []
    for seq in seq_graphs_list: flat_graphs.extend(seq)
    flat_batch = Batch.from_data_list(
        flat_graphs, exclude_keys=['edge_attack_names', 'window_start_unix'])
    struct_tensor = torch.stack(
        [torch.as_tensor(s, dtype=torch.float32) for s in seq_struct_list], dim=0)
    return (flat_batch, B, T, struct_tensor,
            torch.tensor([float(v) for v in y_bin_list],  dtype=torch.float32),
            torch.tensor([int(v)   for v in y_multi_list], dtype=torch.long))

def graph_label(g, thr=ATTACK_THR_DEFAULT):
    return dominant_family(g, thr)

def graph_stats(g):
    n = int(g.x.shape[0]); m = int(g.edge_index.shape[1])
    if n == 0 or m == 0: return n, m, 0.0, 0
    ei = g.edge_index.numpy()
    A  = coo_matrix((np.ones(m, dtype=np.int8), (ei[0], ei[1])), shape=(n, n))
    n_comp, _ = connected_components(A, directed=False)
    return n, m, m / max(n, 1), int(n_comp)

def attack_frac(g):
    names = getattr(g, 'edge_attack_names', None)
    if not names: return 0.0
    return sum(1 for n in names if n != 'Benign') / max(len(names), 1)

def load_split(ds, split):
    return load_pickle(os.path.join(DATASET_CONFIG[ds], f'{split}_graphs.pkl'))

def all_graphs(ds):
    gs = []
    for s in ('train', 'val', 'test'):
        x = load_split(ds, s)
        if x: gs += x
    return gs

print('Graph utilities ready.')

Graph utilities ready.

In [5]:
# =====================================================================
# Cell 5 — Master DB: load or initialise
# =====================================================================
def _empty_db():
    return {
        'meta': {
            'created_utc': datetime.datetime.utcnow().isoformat() + 'Z',
            'schema_version': '1.0',
            'last_updated_utc': datetime.datetime.utcnow().isoformat() + 'Z',
        },
        'baseline': {},   # ds -> method -> metrics
        'ssl':      {},   # ds -> ssl -> metrics
        'tft':      {},   # ds -> ssl -> mode -> {metrics, threshold_sweep, per_class}
    }

if os.path.isfile(MASTER_DB):
    DB = load_json(MASTER_DB)
    for k, v in _empty_db().items():
        DB.setdefault(k, v)
    print(f'[db] loaded {MASTER_DB}')
else:
    DB = _empty_db()
    print(f'[db] created new {MASTER_DB}')

def _count_db():
    nb = sum(len(v) for v in DB['baseline'].values())
    ns = sum(len(v) for v in DB['ssl'].values())
    nt = sum(len(v) for ds in DB['tft'].values() for v in ds.values())
    return nb, ns, nt

nb, ns, nt = _count_db()
print(f'[db] baseline={nb}  ssl={ns}  tft={nt}')

[db] loaded master_db.json
[db] baseline=18  ssl=6  tft=18

In [6]:
# =====================================================================
# Cell 6 — Baseline: detect missing and fill
# =====================================================================
def _baseline_from_json():
    raw = load_json(BASELINE_JSON)
    if raw is None: return
    for ds in DATASET_ORDER:
        if ds not in raw: continue
        for m in BASELINE_METHOD_ORDER:
            if m not in raw[ds]: continue
            r = raw[ds][m]
            def _f(x):
                try: return float(x)
                except Exception: return float('nan')
            DB['baseline'].setdefault(ds, {})[m] = {
                'roc':      _f(r.get('ROC')),
                'pr':       _f(r.get('PR')),
                'f1':       _f(r.get('F1')),
                'fpr':      _f(r.get('FPR')),
                'fnr':      _f(r.get('FNR')),
                'macro_f1': _f(r.get('mF1_multi')),
                'source':   'baseline_benchmark.json',
            }

@torch.no_grad()
def _evaluate_baseline(ds, method):
    ckpt = os.path.join(BASELINE_CKPT_DIR, f'{ds}_{method}_best.pt')
    if not os.path.isfile(ckpt): return None
    # load graphs
    tr = load_split(ds, 'train'); va = load_split(ds, 'val'); te = load_split(ds, 'test')
    if tr is None or va is None or te is None: return None
    ns = load_json(os.path.join(DATASET_CONFIG[ds], 'norm_stats.json'))
    # normalise
    nm = torch.tensor(ns['node_mean'], dtype=torch.float32)
    nstd = torch.tensor(ns['node_std'],  dtype=torch.float32)
    em = torch.tensor(ns['edge_mean'], dtype=torch.float32)
    es = torch.tensor(ns['edge_std'],  dtype=torch.float32)
    for g in tr + va + te:
        g.x = (g.x - nm) / nstd
        g.edge_attr = (g.edge_attr - em) / es
    # labels
    atk = DATASET_THRESHOLDS[ds]
    labels = [dominant_family(g, max(atk, ATTACK_THR_DEFAULT))
              for g in tr + va + te]
    class_names = sorted(set(labels))
    c2i = {c: i for i, c in enumerate(class_names)}
    benign_idx = c2i.get('Benign', 0)
    for g, lab in zip(tr + va + te, labels):
        g.y = torch.tensor([c2i[lab]], dtype=torch.long)
    # model
    node_dim = tr[0].x.shape[1]; edge_dim = tr[0].edge_attr.shape[1]
    model = build_baseline_model(method, node_dim, edge_dim, len(class_names)).to(DEVICE)
    model.load_state_dict(torch.load(ckpt, map_location=DEVICE))
    model.eval()
    def _predict(graphs):
        logits = []
        for b in PyGLoader(graphs, batch_size=64):
            b = b.to(DEVICE)
            logits.append(model(b).cpu())
        logits = torch.cat(logits)
        return F.softmax(logits, -1).numpy()
    pv = _predict(va); pt = _predict(te)
    va_bin = np.array([(int(g.y.item()) != benign_idx) for g in va]).astype(int)
    te_bin = np.array([(int(g.y.item()) != benign_idx) for g in te]).astype(int)
    pt_bin = 1.0 - pt[:, benign_idx]
    pv_bin = 1.0 - pv[:, benign_idx]
    # Youden threshold from val
    fpr, tpr, thr = roc_curve(va_bin, pv_bin)
    thr = float(thr[int(np.argmax(tpr - fpr))])
    pred = (pt_bin >= thr).astype(int)
    cm = confusion_matrix(te_bin, pred, labels=[0, 1])
    tn, fp, fn, tp = cm.ravel()
    y_multi_te = np.array([int(g.y.item()) for g in te])
    ym_pred = pt.argmax(-1)
    return {
        'roc':      float(roc_auc_score(te_bin, pt_bin)),
        'pr':       float(average_precision_score(te_bin, pt_bin)),
        'f1':       float(f1_score(te_bin, pred, zero_division=0)),
        'fpr':      float(fp / max(fp + tn, 1)),
        'fnr':      float(fn / max(fn + tp, 1)),
        'macro_f1': float(f1_score(y_multi_te, ym_pred, average='macro', zero_division=0)),
        'source':   'recomputed',
    }

with safe_section('Baseline: fill missing'):
    if FORCE_RECOMPUTE_ALL or FORCE_RECOMPUTE_BASELINE:
        DB['baseline'] = {}
    _baseline_from_json()  # cheap
    filled, skipped = 0, 0
    for ds in DATASET_ORDER:
        if not os.path.isdir(DATASET_CONFIG[ds]): continue
        for m in BASELINE_METHOD_ORDER:
            existing = DB['baseline'].get(ds, {}).get(m)
            if existing and not (FORCE_RECOMPUTE_ALL or FORCE_RECOMPUTE_BASELINE):
                skipped += 1; continue
            r = _evaluate_baseline(ds, m)
            if r is None:
                print(f'  [miss] {ds}/{m}: no checkpoint')
                continue
            DB['baseline'].setdefault(ds, {})[m] = r
            filled += 1
            print(f'  [add] {ds}/{m}: ROC={r["roc"]:.4f} F1={r["f1"]:.4f}')
    print(f'\n  baseline: {filled} filled, {skipped} skipped')
    save_json(MASTER_DB, DB)

================================================================================
  Baseline: fill missing
================================================================================

  baseline: 0 filled, 18 skipped

In [7]:
# =====================================================================
# Cell 7 — SSL: load (or regenerate) summaries
# =====================================================================
def _ssl_from_json():
    for ssl_name, path in SSL_JSONS.items():
        raw = load_json(path)
        if raw is None: continue
        for ds in DATASET_ORDER:
            if ds not in raw: continue
            r = raw[ds]
            if not isinstance(r, dict): continue
            def _pick(d, *ks):
                for k in ks:
                    if k in d and d[k] is not None:
                        try: return float(d[k])
                        except Exception: pass
                return float('nan')
            DB['ssl'].setdefault(ds, {})[ssl_name] = {
                'roc':      _pick(r, 'test_roc_auc', 'test_roc'),
                'pr':       _pick(r, 'test_pr_auc',  'test_pr'),
                'f1':       _pick(r, 'test_f1_binary', 'test_f1'),
                'fpr':      _pick(r, 'test_fpr'),
                'fnr':      _pick(r, 'test_fnr'),
                'macro_f1': _pick(r, 'test_macro_f1'),
                'source':   os.path.basename(path),
            }

with safe_section('SSL: load summaries'):
    if FORCE_RECOMPUTE_ALL or FORCE_RECOMPUTE_SSL:
        DB['ssl'] = {}
    _ssl_from_json()
    n_added = 0
    for ds in DATASET_ORDER:
        for ssl in SSL_ORDER:
            if DB['ssl'].get(ds, {}).get(ssl): continue
            # try ssl_report.json inside checkpoint dir
            rp = os.path.join(DATASET_CONFIG[ds],
                             f'ssl_checkpoints_{ssl}', 'ssl_report.json')
            rep = load_json(rp)
            if rep is None: continue
            def _pick(*ks):
                for k in ks:
                    if k in rep and rep[k] is not None:
                        try: return float(rep[k])
                        except Exception: pass
                return float('nan')
            DB['ssl'].setdefault(ds, {})[ssl] = {
                'roc':      _pick('test_roc_auc', 'test_roc'),
                'pr':       _pick('test_pr_auc',  'test_pr'),
                'f1':       _pick('test_f1_binary', 'test_f1'),
                'fpr':      _pick('test_fpr'),
                'fnr':      _pick('test_fnr'),
                'macro_f1': _pick('test_macro_f1'),
                'source':   rp,
            }
            n_added += 1
            print(f'  [add] ssl {ds}/{ssl}')
    print(f'  SSL: {n_added} added from reports')
    save_json(MASTER_DB, DB)

================================================================================
  SSL: load summaries
================================================================================
  SSL: 0 added from reports

In [8]:
# =====================================================================
# Cell 8 — TFT: context builder + re-evaluation
# =====================================================================

def _find_frozen_cache(ds, ssl):
    matches = sorted(glob.glob(os.path.join(DATASET_CONFIG[ds],
                                            f'frozen_cache_{ssl}_L*.pt')))
    return matches[-1] if matches else None

def _load_ssl_meta(ds, ssl):
    p = os.path.join(DATASET_CONFIG[ds], f'ssl_checkpoints_{ssl}',
                     'ssl_encoder_best.pth')
    return torch.load(p, map_location='cpu') if os.path.isfile(p) else None

def _load_graphs_norm(ds):
    ddir = DATASET_CONFIG[ds]
    cap = MAX_EDGES_PER_DATASET.get(ds, 20000)
    def _one(s):
        with open(os.path.join(ddir, f'{s}_graphs.pkl'), 'rb') as f:
            return pickle.load(f)
    tg = [cap_graph(g, max_edges=cap) for g in _one('train')]
    vg = [cap_graph(g, max_edges=cap) for g in _one('val')]
    eg = [cap_graph(g, max_edges=cap) for g in _one('test')]
    ns = load_json(os.path.join(ddir, 'norm_stats.json'))
    N_CONT = ns['n_continuous_edge_feats']
    nmean = torch.tensor(ns['node_mean'], dtype=torch.float)
    nstd  = torch.tensor(ns['node_std'],  dtype=torch.float)
    emean = torch.tensor(ns['edge_mean'], dtype=torch.float)
    estd  = torch.tensor(ns['edge_std'],  dtype=torch.float)
    for g in tg + vg + eg:
        g.x = torch.clamp((g.x - nmean) / (nstd + 1e-8), -10, 10)
        if g.edge_attr is not None and g.edge_attr.size(0) > 0:
            if g.edge_attr.dim() > 2:
                g.edge_attr = g.edge_attr.view(-1, g.edge_attr.size(-1))
            c, p = g.edge_attr[:, :N_CONT], g.edge_attr[:, N_CONT:]
            c = torch.clamp((c - emean) / (estd + 1e-8), -10, 10)
            g.edge_attr = torch.cat([c, p], dim=1)
        if g.edge_attr is None or g.edge_attr.size(0) == 0:
            g.edge_attr = torch.zeros((g.edge_index.size(1), N_CONT), dtype=torch.float)
        g.x = torch.nan_to_num(g.x, 0.0, 0.0, 0.0)
        g.edge_attr = torch.nan_to_num(g.edge_attr, 0.0, 0.0, 0.0)
    return tg, vg, eg, ns

def _build_tft_ctx(ds, ssl, finetune):
    meta = _load_ssl_meta(ds, ssl)
    if meta is None: return None
    tg, vg, eg, ns = _load_graphs_norm(ds)
    atk = DATASET_THRESHOLDS[ds]
    tl = np.array([dominant_family(g, atk) for g in tg])
    vl = np.array([dominant_family(g, atk) for g in vg])
    el = np.array([dominant_family(g, atk) for g in eg])
    class_names = sorted(set(tl.tolist()) | set(vl.tolist()) | set(el.tolist()))
    label_to_idx = {c: i for i, c in enumerate(class_names)}
    NUM_CLASSES = len(class_names)
    tb = (tl != 'Benign').astype(np.float32)
    vb = (vl != 'Benign').astype(np.float32)
    eb = (el != 'Benign').astype(np.float32)
    tm = np.array([label_to_idx[c] for c in tl], np.int64)
    vm = np.array([label_to_idx[c] for c in vl], np.int64)
    em = np.array([label_to_idx[c] for c in el], np.int64)
    MWG = float(ns.get('max_window_gap_sec', 60))

    if finetune:
        ts_va = build_gap_aware_starts(vg, SEQUENCE_LENGTH, SEQUENCE_STRIDE, MWG, True)
        ts_te = build_gap_aware_starts(eg, SEQUENCE_LENGTH, SEQUENCE_STRIDE, MWG, True)
        def _seq(y, s): return np.array([y[i + SEQUENCE_LENGTH - 1] for i in s])
        va_yb, te_yb = _seq(vb, ts_va), _seq(eb, ts_te)
        va_ym, te_ym = _seq(vm, ts_va), _seq(em, ts_te)
        str_va = precompute_struct(vg); str_te = precompute_struct(eg)
        NUM_STRUCT = str_va.size(1)
        def _mk(graphs, starts, yb, ym, struct):
            d = GraphSequenceDataset(graphs, starts, SEQUENCE_LENGTH, yb, ym, struct)
            return DataLoader(d, batch_size=EVAL_BATCH_SIZE, shuffle=False,
                              collate_fn=collate_graph_sequences,
                              num_workers=0, pin_memory=(DEVICE.type == 'cuda'))
        val_loader  = _mk(vg, ts_va, va_yb, va_ym, str_va)
        test_loader = _mk(eg, ts_te, te_yb, te_ym, str_te)
        # also per-class label per test sequence
        te_lab = _seq(el, ts_te)
        return dict(mode='finetune', val_loader=val_loader, test_loader=test_loader,
                    NUM_CLASSES=NUM_CLASSES, NUM_STRUCT=NUM_STRUCT,
                    class_names=class_names, te_lab=te_lab, meta=meta)
    else:
        cache_path = _find_frozen_cache(ds, ssl)
        if not cache_path: return None
        payload = torch.load(cache_path, map_location='cpu')
        cache = payload['splits']
        NUM_STRUCT = cache['val'][0][1].size(1)
        def _rebatch(flat, bs=EVAL_BATCH_SIZE):
            out = []
            for i in range(0, len(flat), bs):
                ch = flat[i:i + bs]
                embs = torch.stack([c[0] for c in ch], 0)
                strs = torch.stack([c[1] for c in ch], 0)
                ybs = torch.tensor([float(c[2]) for c in ch], dtype=torch.float32)
                yms = torch.tensor([int(c[3])   for c in ch], dtype=torch.long)
                out.append((embs, strs, ybs, yms))
            return out
        # reconstruct per-graph labels for the test set for per-class analysis
        eg_labels = [dominant_family(g, atk) for g in eg]
        ts_te = build_gap_aware_starts(eg, SEQUENCE_LENGTH, SEQUENCE_STRIDE, MWG, True)
        te_lab = np.array([eg_labels[i + SEQUENCE_LENGTH - 1] for i in ts_te])
        return dict(mode='frozen', val_batches=_rebatch(cache['val']),
                    test_batches=_rebatch(cache['test']),
                    NUM_CLASSES=NUM_CLASSES, NUM_STRUCT=NUM_STRUCT,
                    class_names=class_names, te_lab=te_lab, meta=meta)

@torch.no_grad()
def _eval_tft_frozen(tft, batches):
    tft.eval(); bp, mp, yb, ym = [], [], [], []
    for e, s, ybs, yms in batches:
        ge = e.to(DEVICE).float(); ss = s.to(DEVICE)
        bl, ml, _, _ = tft(ge, ss)
        bp.append(torch.sigmoid(bl.float()).cpu().numpy())
        mp.append(F.softmax(ml.float(), -1).cpu().numpy())
        yb.append(ybs.numpy()); ym.append(yms.numpy())
    return (np.concatenate(bp), np.concatenate(mp),
            np.concatenate(yb), np.concatenate(ym))

@torch.no_grad()
def _eval_tft_finetune(enc, tft, loader):
    enc.eval(); tft.eval(); bp, mp, yb, ym = [], [], [], []
    for fb, B, T, ss, ybs, yms in loader:
        ss = ss.to(DEVICE); b = fb.to(DEVICE)
        h = enc(b.x, b.edge_index, b.edge_attr, b.batch)
        if isinstance(h, tuple): h = h[-1]
        h = h.view(B, T, -1).float()
        bl, ml, _, _ = tft(h, ss)
        bp.append(torch.sigmoid(bl.float()).cpu().numpy())
        mp.append(F.softmax(ml.float(), -1).cpu().numpy())
        yb.append(ybs.numpy()); ym.append(yms.numpy())
    return (np.concatenate(bp), np.concatenate(mp),
            np.concatenate(yb), np.concatenate(ym))

def _threshold_metrics(pb_test, pb_val, yb_test, yb_val, ym_test, pm_test, te_lab):
    yb_v = yb_val.astype(int); yb_t = yb_test.astype(int)
    prec, rec, thr_arr = precision_recall_curve(yb_v, pb_val)
    prec, rec = prec[:-1], rec[:-1]
    f1_arr = 2 * prec * rec / (prec + rec + 1e-12)
    thr_f1 = float(thr_arr[int(np.nanargmax(f1_arr))]) if np.isfinite(f1_arr).any() else 0.5
    fpr_v, tpr_v, thr_v = roc_curve(yb_v, pb_val)
    thr_bal = float(thr_v[int(np.argmax(0.5 * (tpr_v + (1 - fpr_v))))])
    rate = float(yb_v.mean())
    thr_prior = float(np.quantile(pb_val, 1.0 - rate))

    out = {}
    for name, thr in [('f1_optimal', thr_f1),
                      ('balanced',   thr_bal),
                      ('prior_matched', thr_prior)]:
        pred = (pb_test >= thr).astype(int)
        cm = confusion_matrix(yb_t, pred, labels=[0, 1])
        tn, fp, fn, tp = cm.ravel()
        out[name] = {
            'thr':      float(thr),
            'roc':      float(roc_auc_score(yb_t, pb_test)),
            'pr':       float(average_precision_score(yb_t, pb_test)),
            'f1':       float(f1_score(yb_t, pred, zero_division=0)),
            'fpr':      float(fp / max(fp + tn, 1)),
            'fnr':      float(fn / max(fn + tp, 1)),
            'tn': int(tn), 'fp': int(fp), 'fn': int(fn), 'tp': int(tp),
            'macro_f1':    float(f1_score(ym_test, pm_test.argmax(-1),
                                          average='macro', zero_division=0)),
            'weighted_f1': float(f1_score(ym_test, pm_test.argmax(-1),
                                          average='weighted', zero_division=0)),
        }
    return out

def _per_class_breakdown(pb_test, te_lab, class_names, thr):
    rows = []
    for cls in class_names:
        if cls == 'Benign': continue
        mask = (te_lab == cls) | (te_lab == 'Benign')
        y = (te_lab[mask] != 'Benign').astype(int); p = pb_test[mask]
        if len(set(y)) < 2: continue
        try:
            roc = float(roc_auc_score(y, p)); pr = float(average_precision_score(y, p))
        except Exception: continue
        pos = (y == 1)
        rows.append({
            'class': cls, 'n_test': int(pos.sum()),
            'roc_vs_benign': roc, 'pr_vs_benign': pr,
            'mean_prob_attack': float(p[pos].mean()) if pos.sum() > 0 else 0.0,
            'recall_at_thr': float((p[pos] >= thr).sum() / max(int(pos.sum()), 1)),
            'missed_at_thr': int((p[pos] < thr).sum()),
        })
    rows.sort(key=lambda r: -r['roc_vs_benign'])
    return rows

def _read_ckpt_meta(tft_state):
    return dict(
        num_classes=int(tft_state['multi_head.3.weight'].shape[0]),
        num_struct=int(tft_state['temporal.proj_struct.weight'].shape[1]),
        graph_dim=int(tft_state['temporal.proj_graph.weight'].shape[1]),
        tft_hidden=int(tft_state['temporal.proj_graph.weight'].shape[0]),
    )

def _build_tft_from_state(state):
    m = _read_ckpt_meta(state)
    tft = MC_STGAT_IDS(m['graph_dim'], m['num_struct'], m['tft_hidden'],
                       m['num_classes'], TFT_NUM_HEADS, TFT_DROPOUT).to(DEVICE)
    tft.load_state_dict(state); tft.eval()
    return tft

print('TFT eval helpers ready.')

TFT eval helpers ready.

In [9]:
# =====================================================================
# Cell 9 — TFT: fill missing (metrics, sweep, per-class)
# =====================================================================
def _tft_metrics_complete(rec):
    if not rec: return False
    for k in ('roc', 'pr', 'f1', 'fpr', 'fnr'):
        if k not in rec or rec[k] is None: return False
    if 'threshold_sweep' not in rec: return False
    if 'per_class' not in rec: return False
    return True

def _evaluate_tft_config(ds, ssl, mode):
    ddir = DATASET_CONFIG[ds]
    sub  = f'phase3_{mode}_{ssl}'
    rp   = os.path.join(ddir, sub, 'phase3_report.json')
    finetune = 'finetune' in mode
    print(f'    [eval] {ds}/{ssl}/{mode}')
    ctx = _build_tft_ctx(ds, ssl, finetune)
    if ctx is None:
        print(f'      [miss] no ctx'); return None
    try:
        if mode.endswith('_single'):
            ck_path = os.path.join(ddir, sub, 'mc_stgat_ids.pth')
            if not os.path.isfile(ck_path):
                print(f'      [miss] no ckpt'); return None
            ck = torch.load(ck_path, map_location='cpu')
            tft = _build_tft_from_state(ck['tft_state_dict'])
            if finetune and 'encoder_state_dict' in ck:
                enc = GATEncoder(ctx['meta']['node_dim'], ctx['meta']['hidden_dim'],
                                 ctx['meta']['num_heads'], ctx['meta']['num_layers'],
                                 ctx['meta']['edge_dim']).to(DEVICE)
                enc.load_state_dict(ck['encoder_state_dict']); enc.eval()
                pbv, pmv, ybv, ymv = _eval_tft_finetune(enc, tft, ctx['val_loader'])
                pbt, pmt, ybt, ymt = _eval_tft_finetune(enc, tft, ctx['test_loader'])
                del enc
            else:
                pbv, pmv, ybv, ymv = _eval_tft_frozen(tft, ctx['val_batches'])
                pbt, pmt, ybt, ymt = _eval_tft_frozen(tft, ctx['test_batches'])
            del tft
        elif mode.endswith('_ensemble'):
            ck_dir = os.path.join(ddir, sub, 'partial_checkpoints')
            seeds  = sorted(glob.glob(os.path.join(ck_dir, 'best_*_ens*.pth')))
            if not seeds:
                print(f'      [miss] no seeds'); return None
            pbv_l, pbt_l, pmv_l, pmt_l = [], [], [], []
            for f in seeds:
                ck = torch.load(f, map_location='cpu')
                tft = _build_tft_from_state(ck['tft_state_dict'])
                if finetune and 'encoder_state_dict' in ck:
                    enc = GATEncoder(ctx['meta']['node_dim'], ctx['meta']['hidden_dim'],
                                     ctx['meta']['num_heads'], ctx['meta']['num_layers'],
                                     ctx['meta']['edge_dim']).to(DEVICE)
                    enc.load_state_dict(ck['encoder_state_dict']); enc.eval()
                    pbv, pmv, ybv, ymv = _eval_tft_finetune(enc, tft, ctx['val_loader'])
                    pbt, pmt, ybt, ymt = _eval_tft_finetune(enc, tft, ctx['test_loader'])
                    del enc
                else:
                    pbv, pmv, ybv, ymv = _eval_tft_frozen(tft, ctx['val_batches'])
                    pbt, pmt, ybt, ymt = _eval_tft_frozen(tft, ctx['test_batches'])
                del tft
                pbv_l.append(pbv); pbt_l.append(pbt)
                pmv_l.append(pmv); pmt_l.append(pmt)
            pbv = np.mean(pbv_l, axis=0); pbt = np.mean(pbt_l, axis=0)
            pmv = np.mean(pmv_l, axis=0); pmt = np.mean(pmt_l, axis=0)
        else:
            return None

        sweep = _threshold_metrics(pbt, pbv, ybt, ybv, ymt, pmt, ctx['te_lab'])
        primary = sweep['f1_optimal']
        per_class = _per_class_breakdown(pbt, ctx['te_lab'], ctx['class_names'], primary['thr'])

        rec = {
            'roc': primary['roc'], 'pr': primary['pr'], 'f1': primary['f1'],
            'fpr': primary['fpr'], 'fnr': primary['fnr'],
            'macro_f1': primary['macro_f1'], 'weighted_f1': primary['weighted_f1'],
            'tn': primary['tn'], 'fp': primary['fp'],
            'fn': primary['fn'], 'tp': primary['tp'],
            'threshold_sweep': sweep,
            'per_class': per_class,
            'best_epoch': (load_json(rp) or {}).get('best_epoch'),
            'finetune': finetune,
            'source': 'recomputed',
        }
        return rec
    finally:
        del ctx; gc.collect()
        if DEVICE.type == 'cuda': torch.cuda.empty_cache()

with safe_section('TFT: fill missing'):
    if FORCE_RECOMPUTE_ALL or FORCE_RECOMPUTE_TFT:
        DB['tft'] = {}
    # seed from existing phase3_report.json files (fast)
    for ds in DATASET_ORDER:
        ddir = DATASET_CONFIG[ds]
        if not os.path.isdir(ddir): continue
        for ssl in SSL_ORDER:
            for mode in TFT_MODE_ORDER:
                rp = os.path.join(ddir, f'phase3_{mode}_{ssl}', 'phase3_report.json')
                rep = load_json(rp)
                if rep is None: continue
                if (ds, ssl, mode) in [(d,s,m) for d in DB['tft'] for s in DB['tft'][d] for m in DB['tft'][d][s]]:
                    continue
                sweep = rep.get('threshold_sweep', {})
                if sweep and 'per_class' in rep:
                    f1o = sweep.get('f1_optimal', {})
                    DB['tft'].setdefault(ds, {}).setdefault(ssl, {})[mode] = {
                        'roc': f1o.get('roc'), 'pr': f1o.get('pr'),
                        'f1': f1o.get('f1'), 'fpr': f1o.get('fpr'),
                        'fnr': f1o.get('fnr'), 'macro_f1': f1o.get('macro_f1'),
                        'weighted_f1': f1o.get('weighted_f1', float('nan')),
                        'tn': f1o.get('tn'), 'fp': f1o.get('fp'),
                        'fn': f1o.get('fn'), 'tp': f1o.get('tp'),
                        'threshold_sweep': sweep,
                        'per_class': rep.get('per_class', []),
                        'best_epoch': rep.get('best_epoch'),
                        'finetune': bool(rep.get('finetune', False)),
                        'source': 'phase3_report.json',
                    }

    # find missing
    to_fill = []
    for ds in DATASET_ORDER:
        if not os.path.isdir(DATASET_CONFIG[ds]): continue
        for ssl in SSL_ORDER:
            for mode in TFT_MODE_ORDER:
                rec = DB['tft'].get(ds, {}).get(ssl, {}).get(mode)
                if not _tft_metrics_complete(rec):
                    to_fill.append((ds, ssl, mode))

    print(f'\n  [scan] {len(to_fill)} TFT configs missing data')
    for ds, ssl, mode in to_fill:
        rec = _evaluate_tft_config(ds, ssl, mode)
        if rec is None: continue
        DB['tft'].setdefault(ds, {}).setdefault(ssl, {})[mode] = rec
        print(f'    [add] {ds}/{ssl}/{mode}  ROC={rec["roc"]:.4f}  F1={rec["f1"]:.4f}')
    save_json(MASTER_DB, DB)
    nb, ns, nt = _count_db()
    print(f'\n  [db] baseline={nb}  ssl={ns}  tft={nt}')

================================================================================
  TFT: fill missing
================================================================================

  [scan] 6 TFT configs missing data
    [eval] gotham/byol/finetune_ensemble
      [miss] no seeds
    [eval] gotham/moco/finetune_ensemble
      [miss] no seeds
    [eval] nf_bot/byol/finetune_ensemble
      [miss] no seeds
    [eval] nf_bot/moco/finetune_ensemble
      [miss] no seeds
    [eval] nf_ton/byol/finetune_ensemble
      [miss] no seeds
    [eval] nf_ton/moco/finetune_ensemble
      [miss] no seeds

  [db] baseline=18  ssl=6  tft=18

In [10]:
# =====================================================================
# Cell 10 — Flat merged table (from DB)
# =====================================================================
rows = []
for ds in DATASET_ORDER:
    for m in BASELINE_METHOD_ORDER:
        r = DB['baseline'].get(ds, {}).get(m)
        if r: rows.append(dict(family='baseline', dataset=ds, ssl='-',
                               mode=m, **{k: r[k] for k in
                               ['roc','pr','f1','fpr','fnr','macro_f1']}))
    for ssl in SSL_ORDER:
        r = DB['ssl'].get(ds, {}).get(ssl)
        if r: rows.append(dict(family='ssl', dataset=ds, ssl=ssl,
                               mode='linear_probe', **{k: r[k] for k in
                               ['roc','pr','f1','fpr','fnr','macro_f1']}))
    for ssl in SSL_ORDER:
        for mode in TFT_MODE_ORDER:
            r = DB['tft'].get(ds, {}).get(ssl, {}).get(mode)
            if r:
                rows.append(dict(family='tft', dataset=ds, ssl=ssl, mode=mode,
                                 **{k: r.get(k, float('nan')) for k in
                                    ['roc','pr','f1','fpr','fnr','macro_f1']}))

FLAT = pd.DataFrame(rows)
if not FLAT.empty:
    pd.set_option('display.max_rows', None)
    pd.set_option('display.width', 200)
    for c in ['roc','pr','f1','fpr','fnr','macro_f1']:
        if c in FLAT: FLAT[c] = FLAT[c].round(4)
    display(Markdown('### Full merged results (from master_db)'))
    display(FLAT)
else:
    print('No rows in DB yet.')

### Full merged results (from master_db)

      family dataset   ssl             mode     roc      pr      f1     fpr     fnr  macro_f1
0   baseline  gotham     -              mlp  0.9691  0.9590  0.8946  0.0173  0.1604    0.5008
1   baseline  gotham     -              gcn  0.8439  0.7968  0.4940  0.0050  0.6684    0.3265
2   baseline  gotham     -              gat  0.9959  0.9904  0.9657  0.0223  0.0214    0.4750
3   baseline  gotham     -             sage  0.9997  0.9995  0.9920  0.0025  0.0107    0.5101
4   baseline  gotham     -              egs  0.9995  0.9990  0.9892  0.0025  0.0160    0.6702
5   baseline  gotham     -         anomal_e  0.9933  0.9919  0.9764  0.0198  0.0053    0.4816
6        ssl  gotham  byol     linear_probe  0.9932  0.9797  0.9659  0.0248  0.0160    0.9748
7        ssl  gotham  moco     linear_probe  0.9948  0.9876  0.9711  0.0223  0.0107    0.9787
8        tft  gotham  byol    frozen_single  0.9991  0.9977  0.9661  0.0098  0.0420    0.5177
9        tft  gotham  byol  finetune_single  0.9999  0.9997  0.9876  0.0098  0.0000    0.6066
10       tft  gotham  byol  frozen_ensemble  0.9991  0.9975  0.9876  0.0098  0.0000    0.4683
11       tft  gotham  moco    frozen_single  0.9993  0.9984  0.9874  0.0066  0.0084    0.6116
12       tft  gotham  moco  finetune_single  0.9998  0.9996  0.9916  0.0033  0.0084    0.8986
13       tft  gotham  moco  frozen_ensemble  0.9997  0.9993  0.9916  0.0033  0.0084    0.7000
14  baseline  nf_bot     -              mlp  0.8785  0.8955  0.8363  0.7587  0.0027    0.6103
15  baseline  nf_bot     -              gcn  0.9007  0.9224  0.8287  0.8016  0.0027    0.6928
16  baseline  nf_bot     -              gat  0.8904  0.9061  0.8370  0.7587  0.0014    0.7346
17  baseline  nf_bot     -             sage  0.8824  0.9021  0.8411  0.7319  0.0027    0.6824
18  baseline  nf_bot     -              egs  0.8843  0.9038  0.8377  0.7507  0.0027    0.7329
19  baseline  nf_bot     -         anomal_e  0.8582  0.8684  0.9323  0.1984  0.0384    0.8300
20       ssl  nf_bot  byol     linear_probe  0.8818  0.8938  0.4454  0.0831  0.7014    0.5014
21       ssl  nf_bot  moco     linear_probe  0.9111  0.9244  0.4248  0.0509  0.7233    0.4945
22       tft  nf_bot  byol    frozen_single  0.7513  0.8100  0.9287  0.3482  0.0000    0.4776
23       tft  nf_bot  byol  finetune_single  0.9003  0.8963  0.9302  0.3401  0.0000    0.7409
24       tft  nf_bot  byol  frozen_ensemble  0.8751  0.8833  0.7664  0.1377  0.3411    0.5133
25       tft  nf_bot  moco    frozen_single  0.9083  0.9259  0.8891  0.5688  0.0000    0.3010
26       tft  nf_bot  moco  finetune_single  0.8488  0.8710  0.9246  0.3320  0.0143    0.4831
27       tft  nf_bot  moco  frozen_ensemble  0.8778  0.8962  0.9280  0.3234  0.0114    0.5559
28  baseline  nf_ton     -              mlp  0.9863  0.9981  0.9747  0.1378  0.0306    0.8376
29  baseline  nf_ton     -              gcn  0.9871  0.9982  0.9744  0.1799  0.0255    0.8372
30  baseline  nf_ton     -              gat  0.9865  0.9981  0.9760  0.1799  0.0225    0.8675
31  baseline  nf_ton     -             sage  0.9897  0.9986  0.9783  0.1588  0.0208    0.8749
32  baseline  nf_ton     -              egs  0.9886  0.9984  0.9764  0.1313  0.0282    0.8684
33  baseline  nf_ton     -         anomal_e  0.9627  0.9912  0.9694  0.2966  0.0194    0.8248
34       ssl  nf_ton  byol     linear_probe  0.9824  0.9976  0.9579  0.0259  0.0773    0.8662
35       ssl  nf_ton  moco     linear_probe  0.9828  0.9976  0.9566  0.0324  0.0789    0.8622
36       tft  nf_ton  byol    frozen_single  0.9876  0.9984  0.9757  0.0882  0.0364    0.8305
37       tft  nf_ton  byol  finetune_single  0.9837  0.9979  0.9743  0.1075  0.0367    0.8038
38       tft  nf_ton  byol  frozen_ensemble  0.9873  0.9984  0.9749  0.0839  0.0384    0.8578
39       tft  nf_ton  moco    frozen_single  0.9850  0.9980  0.9719  0.0645  0.0466    0.8692
40       tft  nf_ton  moco  finetune_single  0.9845  0.9980  0.9728  0.1871  0.0296    0.8127
41       tft  nf_ton  moco  frozen_ensemble  0.9880  0.9984  0.9738  0.0731  0.0418    0.8826

In [12]:
# =====================================================================
# Cell 11 — Plot: baseline figures
# =====================================================================
def _baseline_norm_split(ds):
    tr = load_split(ds, 'train'); va = load_split(ds, 'val'); te = load_split(ds, 'test')
    if tr is None or va is None or te is None: return None
    ns = load_json(os.path.join(DATASET_CONFIG[ds], 'norm_stats.json'))
    nm = torch.tensor(ns['node_mean'], dtype=torch.float32)
    nstd = torch.tensor(ns['node_std'],  dtype=torch.float32)
    em = torch.tensor(ns['edge_mean'], dtype=torch.float32)
    es = torch.tensor(ns['edge_std'],  dtype=torch.float32)
    allg = tr + va + te
    for g in allg:
        g.x = (g.x - nm) / nstd
        g.edge_attr = (g.edge_attr - em) / es
    atk = DATASET_THRESHOLDS[ds]
    labels = [dominant_family(g, max(atk, ATTACK_THR_DEFAULT)) for g in allg]
    cn = sorted(set(labels)); c2i = {c: i for i, c in enumerate(cn)}
    benign = c2i.get('Benign', 0)
    for g, lab in zip(allg, labels):
        g.y = torch.tensor([c2i[lab]], dtype=torch.long)
    return tr, va, te, cn, benign

with safe_section('Plots: baseline'):
    for ds in DATASET_ORDER:
        out_dir = os.path.join(DIR_BASELINE, ds)
        os.makedirs(out_dir, exist_ok=True)
        split = _baseline_norm_split(ds)
        if split is None: continue
        tr, va, te, cn, bi = split
        va_y = np.array([int(g.y.item()) for g in va])
        te_y = np.array([int(g.y.item()) for g in te])
        va_bin = (va_y != bi).astype(int); te_bin = (te_y != bi).astype(int)
        for m in BASELINE_METHOD_ORDER:
            ckpt = os.path.join(BASELINE_CKPT_DIR, f'{ds}_{m}_best.pt')
            if not os.path.isfile(ckpt): continue
            try:
                nd = tr[0].x.shape[1]; ed = tr[0].edge_attr.shape[1]
                model = build_baseline_model(m, nd, ed, len(cn)).to(DEVICE)
                model.load_state_dict(torch.load(ckpt, map_location=DEVICE))
                model.eval()
                @torch.no_grad()
                def _pred(graphs):
                    L = []
                    for b in PyGLoader(graphs, batch_size=64):
                        b = b.to(DEVICE); L.append(model(b).cpu())
                    L = torch.cat(L); return F.softmax(L, -1).numpy()
                pv = _pred(va); pt = _pred(te)
                pv_bin = 1.0 - pv[:, bi]; pt_bin = 1.0 - pt[:, bi]
                fpr, tpr, _ = roc_curve(te_bin, pt_bin)
                roc = roc_auc_score(te_bin, pt_bin)
                prec, rec, _ = precision_recall_curve(te_bin, pt_bin)
                pr = average_precision_score(te_bin, pt_bin)
                base = float(te_bin.mean())
                fig, ax = plt.subplots(figsize=(7, 6))
                ax.plot(fpr, tpr, lw=2, label=f'ROC-AUC={roc:.4f}')
                ax.plot([0,1],[0,1],'k--',alpha=.4)
                ax.set_xlabel('FPR'); ax.set_ylabel('TPR')
                ax.set_title(f'{ds}/{m} — ROC (baseline)'); ax.legend(); ax.grid(alpha=.3)
                save_fig(fig, os.path.join(out_dir, f'Baseline_{ds}_{m}_roc.png'))
                fig, ax = plt.subplots(figsize=(7, 6))
                ax.plot(rec, prec, lw=2, label=f'PR-AUC={pr:.4f}')
                ax.axhline(base, color='k', ls='--', alpha=.4, label=f'base ({base:.3f})')
                ax.set_xlabel('Recall'); ax.set_ylabel('Precision')
                ax.set_title(f'{ds}/{m} — PR (baseline)'); ax.legend(); ax.grid(alpha=.3)
                save_fig(fig, os.path.join(out_dir, f'Baseline_{ds}_{m}_pr.png'))
                # Confusion
                fprv, tprv, thrv = roc_curve(va_bin, pv_bin)
                thr = float(thrv[int(np.argmax(tprv - fprv))])
                pred = (pt_bin >= thr).astype(int)
                cm = confusion_matrix(te_bin, pred, labels=[0,1])
                cmn = cm / cm.sum(1, keepdims=True).clip(min=1)
                fig, ax = plt.subplots(figsize=(6, 5.5))
                im = ax.imshow(cmn, cmap='Blues', vmin=0, vmax=1)
                for i in range(2):
                    for j in range(2):
                        ax.text(j, i, f'{cm[i,j]}\n({cmn[i,j]:.2%})', ha='center',
                                va='center', fontsize=11,
                                color='white' if cmn[i,j]>0.5 else 'black')
                ax.set_xticks([0,1]); ax.set_yticks([0,1])
                ax.set_xticklabels(['Benign','Attack']); ax.set_yticklabels(['Benign','Attack'])
                ax.set_title(f'{ds}/{m} — confusion (thr={thr:.3f})')
                plt.colorbar(im, ax=ax, fraction=0.045)
                save_fig(fig, os.path.join(out_dir, f'Baseline_{ds}_{m}_confusion.png'))
                del model
            except Exception as e:
                print(f'  [FAIL] {ds}/{m}: {e}')
        # cross-dataset summary
        if (ds == DATASET_ORDER[0]):
            items = []
            for m in BASELINE_METHOD_ORDER:
                r = DB['baseline'].get(ds, {}).get(m)
                if r: items.append((ds, m, r))
            if items:
                metrics = [('roc','ROC'),('pr','PR'),('f1','F1'),('macro_f1','mF1')]
                x = np.arange(len(metrics)); w = 0.8/len(items)
                fig, ax = plt.subplots(figsize=(11, 5))
                cmap = plt.get_cmap('viridis')
                for i, (d_, m_, r_) in enumerate(items):
                    vals = [float(r_.get(k, np.nan)) for k, _ in metrics]
                    bars = ax.bar(x + (i - len(items)/2 + 0.5)*w, vals, width=w,
                                  label=f'{d_}/{m_}', color=cmap(i/max(len(items)-1,1)))
                    for b, v in zip(bars, vals):
                        if np.isfinite(v):
                            ax.text(b.get_x()+b.get_width()/2, v+0.005, f'{v:.3f}',
                                    ha='center', va='bottom', fontsize=6, rotation=90)
                ax.set_xticks(x); ax.set_xticklabels([n for _, n in metrics])
                ax.set_ylim(0, 1.08); ax.set_ylabel('Score')
                ax.set_title('Baseline — summary'); ax.legend(fontsize=8)
                ax.grid(alpha=.3, axis='y')
                save_fig(fig, os.path.join(DIR_BASELINE, 'Baseline_summary.png'))

================================================================================
  Plots: baseline
================================================================================
  [plot] final_plot\baseline_plots\Baseline\gotham\Baseline_gotham_mlp_roc.png
  [plot] final_plot\baseline_plots\Baseline\gotham\Baseline_gotham_mlp_pr.png
  [plot] final_plot\baseline_plots\Baseline\gotham\Baseline_gotham_mlp_confusion.png
  [plot] final_plot\baseline_plots\Baseline\gotham\Baseline_gotham_gcn_roc.png
  [plot] final_plot\baseline_plots\Baseline\gotham\Baseline_gotham_gcn_pr.png
  [plot] final_plot\baseline_plots\Baseline\gotham\Baseline_gotham_gcn_confusion.png
  [plot] final_plot\baseline_plots\Baseline\gotham\Baseline_gotham_gat_roc.png
  [plot] final_plot\baseline_plots\Baseline\gotham\Baseline_gotham_gat_pr.png
  [plot] final_plot\baseline_plots\Baseline\gotham\Baseline_gotham_gat_confusion.png
  [plot] final_plot\baseline_plots\Baseline\gotham\Baseline_gotham_sage_roc.png
  [plot] final_plot\baseline_plots\Baseline\gotham\Baseline_gotham_sage_pr.png
  [plot] final_plot\baseline_plots\Baseline\gotham\Baseline_gotham_sage_confusion.png
  [plot] final_plot\baseline_plots\Baseline\gotham\Baseline_gotham_egs_roc.png
  [plot] final_plot\baseline_plots\Baseline\gotham\Baseline_gotham_egs_pr.png
  [plot] final_plot\baseline_plots\Baseline\gotham\Baseline_gotham_egs_confusion.png
  [plot] final_plot\baseline_plots\Baseline\gotham\Baseline_gotham_anomal_e_roc.png
  [plot] final_plot\baseline_plots\Baseline\gotham\Baseline_gotham_anomal_e_pr.png
  [plot] final_plot\baseline_plots\Baseline\gotham\Baseline_gotham_anomal_e_confusion.png
  [plot] final_plot\baseline_plots\Baseline\Baseline_summary.png
  [plot] final_plot\baseline_plots\Baseline\nf_bot\Baseline_nf_bot_mlp_roc.png
  [plot] final_plot\baseline_plots\Baseline\nf_bot\Baseline_nf_bot_mlp_pr.png
  [plot] final_plot\baseline_plots\Baseline\nf_bot\Baseline_nf_bot_mlp_confusion.png
  [plot] final_plot\baseline_plots\Baseline\nf_bot\Baseline_nf_bot_gcn_roc.png
  [plot] final_plot\baseline_plots\Baseline\nf_bot\Baseline_nf_bot_gcn_pr.png
  [plot] final_plot\baseline_plots\Baseline\nf_bot\Baseline_nf_bot_gcn_confusion.png
  [plot] final_plot\baseline_plots\Baseline\nf_bot\Baseline_nf_bot_gat_roc.png
  [plot] final_plot\baseline_plots\Baseline\nf_bot\Baseline_nf_bot_gat_pr.png
  [plot] final_plot\baseline_plots\Baseline\nf_bot\Baseline_nf_bot_gat_confusion.png
  [plot] final_plot\baseline_plots\Baseline\nf_bot\Baseline_nf_bot_sage_roc.png
  [plot] final_plot\baseline_plots\Baseline\nf_bot\Baseline_nf_bot_sage_pr.png
  [plot] final_plot\baseline_plots\Baseline\nf_bot\Baseline_nf_bot_sage_confusion.png
  [plot] final_plot\baseline_plots\Baseline\nf_bot\Baseline_nf_bot_egs_roc.png
  [plot] final_plot\baseline_plots\Baseline\nf_bot\Baseline_nf_bot_egs_pr.png
  [plot] final_plot\baseline_plots\Baseline\nf_bot\Baseline_nf_bot_egs_confusion.png
  [plot] final_plot\baseline_plots\Baseline\nf_bot\Baseline_nf_bot_anomal_e_roc.png
  [plot] final_plot\baseline_plots\Baseline\nf_bot\Baseline_nf_bot_anomal_e_pr.png
  [plot] final_plot\baseline_plots\Baseline\nf_bot\Baseline_nf_bot_anomal_e_confusion.png
  [plot] final_plot\baseline_plots\Baseline\nf_ton\Baseline_nf_ton_mlp_roc.png
  [plot] final_plot\baseline_plots\Baseline\nf_ton\Baseline_nf_ton_mlp_pr.png
  [plot] final_plot\baseline_plots\Baseline\nf_ton\Baseline_nf_ton_mlp_confusion.png
  [plot] final_plot\baseline_plots\Baseline\nf_ton\Baseline_nf_ton_gcn_roc.png
  [plot] final_plot\baseline_plots\Baseline\nf_ton\Baseline_nf_ton_gcn_pr.png
  [plot] final_plot\baseline_plots\Baseline\nf_ton\Baseline_nf_ton_gcn_confusion.png
  [plot] final_plot\baseline_plots\Baseline\nf_ton\Baseline_nf_ton_gat_roc.png
  [plot] final_plot\baseline_plots\Baseline\nf_ton\Baseline_nf_ton_gat_pr.png
  [plot] final_plot\baseline_plots\Baseline\nf_ton\Baseline_nf_ton_gat_confusion.png
  [plot] final_plot\baseline_plots\Baseline\nf_ton\Baseline_nf_ton_sage_roc.png
  [plot] final_plot\baseline_plots\Baseline\nf_ton\Baseline_nf_ton_sage_pr.png
  [plot] final_plot\baseline_plots\Baseline\nf_ton\Baseline_nf_ton_sage_confusion.png
  [plot] final_plot\baseline_plots\Baseline\nf_ton\Baseline_nf_ton_egs_roc.png
  [plot] final_plot\baseline_plots\Baseline\nf_ton\Baseline_nf_ton_egs_pr.png
  [plot] final_plot\baseline_plots\Baseline\nf_ton\Baseline_nf_ton_egs_confusion.png
  [plot] final_plot\baseline_plots\Baseline\nf_ton\Baseline_nf_ton_anomal_e_roc.png
  [plot] final_plot\baseline_plots\Baseline\nf_ton\Baseline_nf_ton_anomal_e_pr.png
  [plot] final_plot\baseline_plots\Baseline\nf_ton\Baseline_nf_ton_anomal_e_confusion.png

In [13]:
# =====================================================================
# Cell 12 — Plot: TFT phase-3 figures (from DB, threshold_sweep, per_class)
# =====================================================================
def _dir_tag(ds, ssl, stage, ft):
    return f"{ds}_{ssl}_{stage}_{'finetune' if ft else 'frozen'}"

def _plot_metrics_bars(t, title, out_path):
    keys = ['roc', 'pr', 'f1', 'weighted_f1', 'macro_f1']
    vals = []
    for k in keys:
        v = t.get(k, float('nan'))
        try: v = float(v)
        except Exception: v = float('nan')
        if k == 'weighted_f1' and not np.isfinite(v):
            try: v = float(t.get('macro_f1', float('nan')))
            except Exception: v = float('nan')
        vals.append(v)
    colors = ['#4C72B0', '#55A868', '#C44E52', '#DD8452', '#8172B2']
    fig, ax = plt.subplots(figsize=(7.5, 4.2))
    bars = ax.bar(keys, vals, color=colors)
    for b, v in zip(bars, vals):
        if np.isfinite(v):
            ax.text(b.get_x()+b.get_width()/2, v+0.01, f'{v:.4f}',
                    ha='center', fontsize=10)
    ax.set_ylim(0, 1.12); ax.set_ylabel('Score'); ax.set_title(title)
    ax.grid(alpha=0.3, axis='y')
    save_fig(fig, out_path)

def _plot_confusion(t, title, out_path):
    tn, fp = int(t.get('tn', 0)), int(t.get('fp', 0))
    fn, tp = int(t.get('fn', 0)), int(t.get('tp', 0))
    if (tn + fp + fn + tp) == 0 and float(t.get('f1', 0) or 0) > 0.1:
        print(f'  [WARN] {title}: confusion counts missing'); return
    cm = np.array([[tn, fp], [fn, tp]])
    cmn = cm / cm.sum(1, keepdims=True).clip(min=1)
    fig, ax = plt.subplots(figsize=(6, 5.2))
    im = ax.imshow(cmn, cmap='Blues', vmin=0, vmax=1)
    for i in range(2):
        for j in range(2):
            ax.text(j, i, f'{cm[i,j]}\n({cmn[i,j]:.2%})', ha='center', va='center',
                    fontsize=12, color='white' if cmn[i,j] > 0.5 else 'black')
    ax.set_xticks([0,1]); ax.set_yticks([0,1])
    ax.set_xticklabels(['Benign','Attack']); ax.set_yticklabels(['Benign','Attack'])
    ax.set_xlabel('Predicted'); ax.set_ylabel('True'); ax.set_title(title)
    plt.colorbar(im, ax=ax, fraction=0.045)
    save_fig(fig, out_path)

def _plot_fpr_fnr(t, title, out_path):
    try: fpr = float(t.get('fpr', float('nan')))
    except Exception: fpr = float('nan')
    try: fnr = float(t.get('fnr', float('nan')))
    except Exception: fnr = float('nan')
    fig, ax = plt.subplots(figsize=(5.5, 4.2))
    bars = ax.bar(['FPR','FNR'], [fpr, fnr], color=['#DD8452','#55A868'])
    for b, v in zip(bars, [fpr, fnr]):
        if np.isfinite(v):
            ax.text(b.get_x()+b.get_width()/2, v+0.01, f'{v:.4f}',
                    ha='center', fontsize=11)
    ax.set_ylim(0, max(1.0, np.nanmax([fpr, fnr])*1.25))
    ax.set_ylabel('Rate'); ax.set_title(title); ax.grid(alpha=.3, axis='y')
    save_fig(fig, out_path)

def _plot_per_class_bar(pc, field, xlabel, title, out_path,
                        xlim=(0,1.05), ref_lines=((0.5,':'),(0.9,'--'))):
    rows = [r for r in pc if r.get(field) is not None
                              and np.isfinite(float(r.get(field, np.nan)))]
    if not rows: return
    rows = sorted(rows, key=lambda r: float(r.get(field, 0)))
    names = [r['class'] for r in rows]; vals = [float(r[field]) for r in rows]
    ns = [int(r.get('n_test', 0)) for r in rows]
    fig, ax = plt.subplots(figsize=(9, max(2.8, 0.4 * len(names))))
    y = np.arange(len(names))
    def _color(v):
        if v < 0.6:  return '#C44E52'
        if v < 0.85: return '#DD8452'
        return '#55A868'
    bars = ax.barh(y, vals, color=[_color(v) for v in vals])
    for b, v, n in zip(bars, vals, ns):
        ax.text(min(v+0.01, xlim[1]-0.02), b.get_y()+b.get_height()/2,
                f'{v:.3f} (n={n})', va='center', fontsize=9)
    ax.set_yticks(y); ax.set_yticklabels(names, fontsize=9)
    ax.set_xlim(*xlim); ax.set_xlabel(xlabel)
    for pos, style in ref_lines: ax.axvline(pos, color='k', ls=style, alpha=0.3)
    ax.set_title(title); ax.grid(alpha=0.3, axis='x')
    save_fig(fig, out_path)

def _plot_per_class_count(pc, title, out_path):
    rows = sorted(pc, key=lambda r: -int(r.get('n_test', 0)))
    if not rows: return
    names = [r['class'] for r in rows]; ns = [int(r.get('n_test', 0)) for r in rows]
    fig, ax = plt.subplots(figsize=(9, max(2.8, 0.4 * len(names))))
    y = np.arange(len(names))
    bars = ax.barh(y, ns, color='#4C72B0')
    for b, n in zip(bars, ns):
        ax.text(b.get_width()+0.5, b.get_y()+b.get_height()/2, f'{n}',
                va='center', fontsize=9)
    ax.set_yticks(y); ax.set_yticklabels(names, fontsize=9)
    ax.set_xlabel('Number of test graphs'); ax.set_title(title)
    ax.grid(alpha=0.3, axis='x')
    save_fig(fig, out_path)

with safe_section('Plots: TFT per config + cross-config'):
    rows_summary = []
    for ds in DATASET_ORDER:
        for ssl in SSL_ORDER:
            for mode in TFT_MODE_ORDER:
                r = DB['tft'].get(ds, {}).get(ssl, {}).get(mode)
                if not r: continue
                ft = bool(r.get('finetune', False))
                plot_root = DIR_TFT_BYOL if ssl == 'byol' else DIR_TFT_MOCO
                out = os.path.join(plot_root, _dir_tag(ds, ssl, mode, ft))
                os.makedirs(out, exist_ok=True)
                tp = f'{ds} · {ssl.upper()} · {mode} · {"finetune" if ft else "frozen"}'
                _plot_metrics_bars(r, f'{tp} — binary metrics',
                                    os.path.join(out, '01_metrics.png'))
                _plot_confusion(r, f'{tp} — confusion',
                                 os.path.join(out, '02_confusion.png'))
                _plot_fpr_fnr(r, f'{tp} — error rates',
                               os.path.join(out, '03_fpr_fnr.png'))
                pc = r.get('per_class', []) or []
                if pc:
                    _plot_per_class_bar(pc, 'roc_vs_benign', 'ROC vs Benign',
                                         f'{tp} — per-class ROC',
                                         os.path.join(out, '04_per_class_roc.png'),
                                         xlim=(0, 1.10))
                    _plot_per_class_bar(pc, 'pr_vs_benign', 'PR vs Benign',
                                         f'{tp} — per-class PR',
                                         os.path.join(out, '05_per_class_pr.png'),
                                         xlim=(0, 1.10))
                    _plot_per_class_bar(pc, 'recall_at_thr', 'Recall at threshold',
                                         f'{tp} — per-class recall',
                                         os.path.join(out, '06_per_class_recall.png'),
                                         xlim=(0, 1.10))
                    _plot_per_class_bar(pc, 'mean_prob_attack', 'Mean predicted prob.',
                                         f'{tp} — mean attack probability per class',
                                         os.path.join(out, '07_per_class_mean_prob.png'),
                                         xlim=(0, 1.10), ref_lines=((0.5,'--'),))
                    _plot_per_class_count(pc, f'{tp} — test class distribution',
                                            os.path.join(out, '08_per_class_count.png'))
                rows_summary.append(dict(ds=ds, ssl=ssl, mode=mode, ft=ft, rec=r))

    for ssl_t, plot_root in (('byol', DIR_TFT_BYOL), ('moco', DIR_TFT_MOCO)):
        rs = [r for r in rows_summary if r['ssl'] == ssl_t]
        if not rs: continue
        labels = [f"{r['ds']}\n{r['mode']}\n{'FT' if r['ft'] else 'FR'}" for r in rs]
        x = np.arange(len(rs)); w = 0.16
        fig, ax = plt.subplots(figsize=(max(9, 1.0 * len(rs)), 5.2))
        cmap = plt.get_cmap('viridis')
        for i, key in enumerate(['roc', 'pr', 'f1', 'macro_f1', 'weighted_f1']):
            vals = [float(r['rec'].get(key, float('nan'))) for r in rs]
            bars = ax.bar(x + (i - 2) * w, vals, width=w, label=key.upper(),
                          color=cmap(i / 4))
            for b, v in zip(bars, vals):
                if np.isfinite(v):
                    ax.text(b.get_x()+b.get_width()/2, v+0.005, f'{v:.3f}',
                            ha='center', va='bottom', fontsize=7, rotation=90)
        ax.set_xticks(x); ax.set_xticklabels(labels, fontsize=8)
        ax.set_ylim(0, 1.12); ax.set_ylabel('Score')
        ax.set_title(f'Phase-3 TFT — {ssl_t.upper()} cross-configuration summary')
        ax.legend(loc='lower right', ncol=5, fontsize=9); ax.grid(alpha=.3, axis='y')
        save_fig(fig, os.path.join(plot_root, '00_cross_config.png'))

================================================================================
  Plots: TFT per config + cross-config
================================================================================
  [plot] final_plot\phase3_plots\gotham_byol_frozen_single_frozen\01_metrics.png
  [plot] final_plot\phase3_plots\gotham_byol_frozen_single_frozen\02_confusion.png
  [plot] final_plot\phase3_plots\gotham_byol_frozen_single_frozen\03_fpr_fnr.png
  [plot] final_plot\phase3_plots\gotham_byol_frozen_single_frozen\04_per_class_roc.png
  [plot] final_plot\phase3_plots\gotham_byol_frozen_single_frozen\05_per_class_pr.png
  [plot] final_plot\phase3_plots\gotham_byol_frozen_single_frozen\06_per_class_recall.png
  [plot] final_plot\phase3_plots\gotham_byol_frozen_single_frozen\07_per_class_mean_prob.png
  [plot] final_plot\phase3_plots\gotham_byol_frozen_single_frozen\08_per_class_count.png
  [plot] final_plot\phase3_plots\gotham_byol_finetune_single_finetune\01_metrics.png
  [plot] final_plot\phase3_plots\gotham_byol_finetune_single_finetune\02_confusion.png
  [plot] final_plot\phase3_plots\gotham_byol_finetune_single_finetune\03_fpr_fnr.png
  [plot] final_plot\phase3_plots\gotham_byol_finetune_single_finetune\04_per_class_roc.png
  [plot] final_plot\phase3_plots\gotham_byol_finetune_single_finetune\05_per_class_pr.png
  [plot] final_plot\phase3_plots\gotham_byol_finetune_single_finetune\06_per_class_recall.png
  [plot] final_plot\phase3_plots\gotham_byol_finetune_single_finetune\07_per_class_mean_prob.png
  [plot] final_plot\phase3_plots\gotham_byol_finetune_single_finetune\08_per_class_count.png
  [plot] final_plot\phase3_plots\gotham_byol_frozen_ensemble_frozen\01_metrics.png
  [plot] final_plot\phase3_plots\gotham_byol_frozen_ensemble_frozen\02_confusion.png
  [plot] final_plot\phase3_plots\gotham_byol_frozen_ensemble_frozen\03_fpr_fnr.png
  [plot] final_plot\phase3_plots\gotham_byol_frozen_ensemble_frozen\04_per_class_roc.png
  [plot] final_plot\phase3_plots\gotham_byol_frozen_ensemble_frozen\05_per_class_pr.png
  [plot] final_plot\phase3_plots\gotham_byol_frozen_ensemble_frozen\06_per_class_recall.png
  [plot] final_plot\phase3_plots\gotham_byol_frozen_ensemble_frozen\07_per_class_mean_prob.png
  [plot] final_plot\phase3_plots\gotham_byol_frozen_ensemble_frozen\08_per_class_count.png
  [plot] final_plot\phase3_plots_moco\gotham_moco_frozen_single_frozen\01_metrics.png
  [plot] final_plot\phase3_plots_moco\gotham_moco_frozen_single_frozen\02_confusion.png
  [plot] final_plot\phase3_plots_moco\gotham_moco_frozen_single_frozen\03_fpr_fnr.png
  [plot] final_plot\phase3_plots_moco\gotham_moco_frozen_single_frozen\04_per_class_roc.png
  [plot] final_plot\phase3_plots_moco\gotham_moco_frozen_single_frozen\05_per_class_pr.png
  [plot] final_plot\phase3_plots_moco\gotham_moco_frozen_single_frozen\06_per_class_recall.png
  [plot] final_plot\phase3_plots_moco\gotham_moco_frozen_single_frozen\07_per_class_mean_prob.png
  [plot] final_plot\phase3_plots_moco\gotham_moco_frozen_single_frozen\08_per_class_count.png
  [plot] final_plot\phase3_plots_moco\gotham_moco_finetune_single_finetune\01_metrics.png
  [plot] final_plot\phase3_plots_moco\gotham_moco_finetune_single_finetune\02_confusion.png
  [plot] final_plot\phase3_plots_moco\gotham_moco_finetune_single_finetune\03_fpr_fnr.png
  [plot] final_plot\phase3_plots_moco\gotham_moco_finetune_single_finetune\04_per_class_roc.png
  [plot] final_plot\phase3_plots_moco\gotham_moco_finetune_single_finetune\05_per_class_pr.png
  [plot] final_plot\phase3_plots_moco\gotham_moco_finetune_single_finetune\06_per_class_recall.png
  [plot] final_plot\phase3_plots_moco\gotham_moco_finetune_single_finetune\07_per_class_mean_prob.png
  [plot] final_plot\phase3_plots_moco\gotham_moco_finetune_single_finetune\08_per_class_count.png
  [plot] final_plot\phase3_plots_moco\gotham_moco_frozen_ensemble_frozen\01_metrics.png
  [plot] final_plot\phase3_plots_moco\gotham_moco_frozen_ensemble_frozen\02_confusion.png
  [plot] final_plot\phase3_plots_moco\gotham_moco_frozen_ensemble_frozen\03_fpr_fnr.png
  [plot] final_plot\phase3_plots_moco\gotham_moco_frozen_ensemble_frozen\04_per_class_roc.png
  [plot] final_plot\phase3_plots_moco\gotham_moco_frozen_ensemble_frozen\05_per_class_pr.png
  [plot] final_plot\phase3_plots_moco\gotham_moco_frozen_ensemble_frozen\06_per_class_recall.png
  [plot] final_plot\phase3_plots_moco\gotham_moco_frozen_ensemble_frozen\07_per_class_mean_prob.png
  [plot] final_plot\phase3_plots_moco\gotham_moco_frozen_ensemble_frozen\08_per_class_count.png
  [plot] final_plot\phase3_plots\nf_bot_byol_frozen_single_frozen\01_metrics.png
  [plot] final_plot\phase3_plots\nf_bot_byol_frozen_single_frozen\02_confusion.png
  [plot] final_plot\phase3_plots\nf_bot_byol_frozen_single_frozen\03_fpr_fnr.png
  [plot] final_plot\phase3_plots\nf_bot_byol_frozen_single_frozen\04_per_class_roc.png
  [plot] final_plot\phase3_plots\nf_bot_byol_frozen_single_frozen\05_per_class_pr.png
  [plot] final_plot\phase3_plots\nf_bot_byol_frozen_single_frozen\06_per_class_recall.png
  [plot] final_plot\phase3_plots\nf_bot_byol_frozen_single_frozen\07_per_class_mean_prob.png
  [plot] final_plot\phase3_plots\nf_bot_byol_frozen_single_frozen\08_per_class_count.png
  [plot] final_plot\phase3_plots\nf_bot_byol_finetune_single_finetune\01_metrics.png
  [plot] final_plot\phase3_plots\nf_bot_byol_finetune_single_finetune\02_confusion.png
  [plot] final_plot\phase3_plots\nf_bot_byol_finetune_single_finetune\03_fpr_fnr.png
  [plot] final_plot\phase3_plots\nf_bot_byol_finetune_single_finetune\04_per_class_roc.png
  [plot] final_plot\phase3_plots\nf_bot_byol_finetune_single_finetune\05_per_class_pr.png
  [plot] final_plot\phase3_plots\nf_bot_byol_finetune_single_finetune\06_per_class_recall.png
  [plot] final_plot\phase3_plots\nf_bot_byol_finetune_single_finetune\07_per_class_mean_prob.png
  [plot] final_plot\phase3_plots\nf_bot_byol_finetune_single_finetune\08_per_class_count.png
  [plot] final_plot\phase3_plots\nf_bot_byol_frozen_ensemble_frozen\01_metrics.png
  [plot] final_plot\phase3_plots\nf_bot_byol_frozen_ensemble_frozen\02_confusion.png
  [plot] final_plot\phase3_plots\nf_bot_byol_frozen_ensemble_frozen\03_fpr_fnr.png
  [plot] final_plot\phase3_plots\nf_bot_byol_frozen_ensemble_frozen\04_per_class_roc.png
  [plot] final_plot\phase3_plots\nf_bot_byol_frozen_ensemble_frozen\05_per_class_pr.png
  [plot] final_plot\phase3_plots\nf_bot_byol_frozen_ensemble_frozen\06_per_class_recall.png
  [plot] final_plot\phase3_plots\nf_bot_byol_frozen_ensemble_frozen\07_per_class_mean_prob.png
  [plot] final_plot\phase3_plots\nf_bot_byol_frozen_ensemble_frozen\08_per_class_count.png
  [plot] final_plot\phase3_plots_moco\nf_bot_moco_frozen_single_frozen\01_metrics.png
  [plot] final_plot\phase3_plots_moco\nf_bot_moco_frozen_single_frozen\02_confusion.png
  [plot] final_plot\phase3_plots_moco\nf_bot_moco_frozen_single_frozen\03_fpr_fnr.png
  [plot] final_plot\phase3_plots_moco\nf_bot_moco_frozen_single_frozen\04_per_class_roc.png
  [plot] final_plot\phase3_plots_moco\nf_bot_moco_frozen_single_frozen\05_per_class_pr.png
  [plot] final_plot\phase3_plots_moco\nf_bot_moco_frozen_single_frozen\06_per_class_recall.png
  [plot] final_plot\phase3_plots_moco\nf_bot_moco_frozen_single_frozen\07_per_class_mean_prob.png
  [plot] final_plot\phase3_plots_moco\nf_bot_moco_frozen_single_frozen\08_per_class_count.png
  [plot] final_plot\phase3_plots_moco\nf_bot_moco_finetune_single_finetune\01_metrics.png
  [plot] final_plot\phase3_plots_moco\nf_bot_moco_finetune_single_finetune\02_confusion.png
  [plot] final_plot\phase3_plots_moco\nf_bot_moco_finetune_single_finetune\03_fpr_fnr.png
  [plot] final_plot\phase3_plots_moco\nf_bot_moco_finetune_single_finetune\04_per_class_roc.png
  [plot] final_plot\phase3_plots_moco\nf_bot_moco_finetune_single_finetune\05_per_class_pr.png
  [plot] final_plot\phase3_plots_moco\nf_bot_moco_finetune_single_finetune\06_per_class_recall.png
  [plot] final_plot\phase3_plots_moco\nf_bot_moco_finetune_single_finetune\07_per_class_mean_prob.png
  [plot] final_plot\phase3_plots_moco\nf_bot_moco_finetune_single_finetune\08_per_class_count.png
  [plot] final_plot\phase3_plots_moco\nf_bot_moco_frozen_ensemble_frozen\01_metrics.png
  [plot] final_plot\phase3_plots_moco\nf_bot_moco_frozen_ensemble_frozen\02_confusion.png
  [plot] final_plot\phase3_plots_moco\nf_bot_moco_frozen_ensemble_frozen\03_fpr_fnr.png
  [plot] final_plot\phase3_plots_moco\nf_bot_moco_frozen_ensemble_frozen\04_per_class_roc.png
  [plot] final_plot\phase3_plots_moco\nf_bot_moco_frozen_ensemble_frozen\05_per_class_pr.png
  [plot] final_plot\phase3_plots_moco\nf_bot_moco_frozen_ensemble_frozen\06_per_class_recall.png
  [plot] final_plot\phase3_plots_moco\nf_bot_moco_frozen_ensemble_frozen\07_per_class_mean_prob.png
  [plot] final_plot\phase3_plots_moco\nf_bot_moco_frozen_ensemble_frozen\08_per_class_count.png
  [plot] final_plot\phase3_plots\nf_ton_byol_frozen_single_frozen\01_metrics.png
  [plot] final_plot\phase3_plots\nf_ton_byol_frozen_single_frozen\02_confusion.png
  [plot] final_plot\phase3_plots\nf_ton_byol_frozen_single_frozen\03_fpr_fnr.png
  [plot] final_plot\phase3_plots\nf_ton_byol_frozen_single_frozen\04_per_class_roc.png
  [plot] final_plot\phase3_plots\nf_ton_byol_frozen_single_frozen\05_per_class_pr.png
  [plot] final_plot\phase3_plots\nf_ton_byol_frozen_single_frozen\06_per_class_recall.png
  [plot] final_plot\phase3_plots\nf_ton_byol_frozen_single_frozen\07_per_class_mean_prob.png
  [plot] final_plot\phase3_plots\nf_ton_byol_frozen_single_frozen\08_per_class_count.png
  [plot] final_plot\phase3_plots\nf_ton_byol_finetune_single_finetune\01_metrics.png
  [plot] final_plot\phase3_plots\nf_ton_byol_finetune_single_finetune\02_confusion.png
  [plot] final_plot\phase3_plots\nf_ton_byol_finetune_single_finetune\03_fpr_fnr.png
  [plot] final_plot\phase3_plots\nf_ton_byol_finetune_single_finetune\04_per_class_roc.png
  [plot] final_plot\phase3_plots\nf_ton_byol_finetune_single_finetune\05_per_class_pr.png
  [plot] final_plot\phase3_plots\nf_ton_byol_finetune_single_finetune\06_per_class_recall.png
  [plot] final_plot\phase3_plots\nf_ton_byol_finetune_single_finetune\07_per_class_mean_prob.png
  [plot] final_plot\phase3_plots\nf_ton_byol_finetune_single_finetune\08_per_class_count.png
  [plot] final_plot\phase3_plots\nf_ton_byol_frozen_ensemble_frozen\01_metrics.png
  [plot] final_plot\phase3_plots\nf_ton_byol_frozen_ensemble_frozen\02_confusion.png
  [plot] final_plot\phase3_plots\nf_ton_byol_frozen_ensemble_frozen\03_fpr_fnr.png
  [plot] final_plot\phase3_plots\nf_ton_byol_frozen_ensemble_frozen\04_per_class_roc.png
  [plot] final_plot\phase3_plots\nf_ton_byol_frozen_ensemble_frozen\05_per_class_pr.png
  [plot] final_plot\phase3_plots\nf_ton_byol_frozen_ensemble_frozen\06_per_class_recall.png
  [plot] final_plot\phase3_plots\nf_ton_byol_frozen_ensemble_frozen\07_per_class_mean_prob.png
  [plot] final_plot\phase3_plots\nf_ton_byol_frozen_ensemble_frozen\08_per_class_count.png
  [plot] final_plot\phase3_plots_moco\nf_ton_moco_frozen_single_frozen\01_metrics.png
  [plot] final_plot\phase3_plots_moco\nf_ton_moco_frozen_single_frozen\02_confusion.png
  [plot] final_plot\phase3_plots_moco\nf_ton_moco_frozen_single_frozen\03_fpr_fnr.png
  [plot] final_plot\phase3_plots_moco\nf_ton_moco_frozen_single_frozen\04_per_class_roc.png
  [plot] final_plot\phase3_plots_moco\nf_ton_moco_frozen_single_frozen\05_per_class_pr.png
  [plot] final_plot\phase3_plots_moco\nf_ton_moco_frozen_single_frozen\06_per_class_recall.png
  [plot] final_plot\phase3_plots_moco\nf_ton_moco_frozen_single_frozen\07_per_class_mean_prob.png
  [plot] final_plot\phase3_plots_moco\nf_ton_moco_frozen_single_frozen\08_per_class_count.png
  [plot] final_plot\phase3_plots_moco\nf_ton_moco_finetune_single_finetune\01_metrics.png
  [plot] final_plot\phase3_plots_moco\nf_ton_moco_finetune_single_finetune\02_confusion.png
  [plot] final_plot\phase3_plots_moco\nf_ton_moco_finetune_single_finetune\03_fpr_fnr.png
  [plot] final_plot\phase3_plots_moco\nf_ton_moco_finetune_single_finetune\04_per_class_roc.png
  [plot] final_plot\phase3_plots_moco\nf_ton_moco_finetune_single_finetune\05_per_class_pr.png
  [plot] final_plot\phase3_plots_moco\nf_ton_moco_finetune_single_finetune\06_per_class_recall.png
  [plot] final_plot\phase3_plots_moco\nf_ton_moco_finetune_single_finetune\07_per_class_mean_prob.png
  [plot] final_plot\phase3_plots_moco\nf_ton_moco_finetune_single_finetune\08_per_class_count.png
  [plot] final_plot\phase3_plots_moco\nf_ton_moco_frozen_ensemble_frozen\01_metrics.png
  [plot] final_plot\phase3_plots_moco\nf_ton_moco_frozen_ensemble_frozen\02_confusion.png
  [plot] final_plot\phase3_plots_moco\nf_ton_moco_frozen_ensemble_frozen\03_fpr_fnr.png
  [plot] final_plot\phase3_plots_moco\nf_ton_moco_frozen_ensemble_frozen\04_per_class_roc.png
  [plot] final_plot\phase3_plots_moco\nf_ton_moco_frozen_ensemble_frozen\05_per_class_pr.png
  [plot] final_plot\phase3_plots_moco\nf_ton_moco_frozen_ensemble_frozen\06_per_class_recall.png
  [plot] final_plot\phase3_plots_moco\nf_ton_moco_frozen_ensemble_frozen\07_per_class_mean_prob.png
  [plot] final_plot\phase3_plots_moco\nf_ton_moco_frozen_ensemble_frozen\08_per_class_count.png
  [plot] final_plot\phase3_plots\00_cross_config.png
  [plot] final_plot\phase3_plots_moco\00_cross_config.png

In [14]:
# =====================================================================
# Cell 13 — Plot: threshold sensitivity (from DB)
# =====================================================================
with safe_section('Plots: threshold sensitivity (3 rules per config)'):
    ts_rows = []
    for ds in DATASET_ORDER:
        for ssl in SSL_ORDER:
            for mode in TFT_MODE_ORDER:
                r = DB['tft'].get(ds, {}).get(ssl, {}).get(mode)
                if not r: continue
                sw = r.get('threshold_sweep', {}) or {}
                if not sw: continue
                ts_rows.append(dict(ds=ds, ssl=ssl, mode=mode, sw=sw))
    if ts_rows:
        labels = [f"{r['ds']}\n{r['ssl']}\n{r['mode']}" for r in ts_rows]
        x = np.arange(len(ts_rows)); w = 0.25
        fig, ax = plt.subplots(figsize=(max(10, 1.0*len(ts_rows)), 5.2))
        for i, rule in enumerate(['f1_optimal', 'balanced', 'prior_matched']):
            vals = [float(r['sw'].get(rule, {}).get('f1', float('nan')))
                    for r in ts_rows]
            bars = ax.bar(x + (i - 1) * w, vals, width=w, label=rule)
            for b, v in zip(bars, vals):
                if np.isfinite(v):
                    ax.text(b.get_x()+b.get_width()/2, v+0.005, f'{v:.3f}',
                            ha='center', va='bottom', fontsize=7, rotation=90)
        ax.set_xticks(x); ax.set_xticklabels(labels, fontsize=7)
        ax.set_ylim(0, 1.12); ax.set_ylabel('F1 at rule')
        ax.set_title('Threshold sensitivity — F1 under three rules')
        ax.legend(); ax.grid(alpha=0.3, axis='y')
        save_fig(fig, os.path.join(FINAL_ROOT, 'threshold_sensitivity.png'))

        # Also produce a table
        trows = []
        for r in ts_rows:
            for rule in ['f1_optimal', 'balanced', 'prior_matched']:
                m = r['sw'].get(rule, {}) or {}
                trows.append(dict(dataset=r['ds'], ssl=r['ssl'], mode=r['mode'],
                                  rule=rule,
                                  thr=float(m.get('thr', float('nan'))),
                                  roc=float(m.get('roc', float('nan'))),
                                  pr=float(m.get('pr', float('nan'))),
                                  f1=float(m.get('f1', float('nan'))),
                                  fpr=float(m.get('fpr', float('nan'))),
                                  fnr=float(m.get('fnr', float('nan')))))
        ts_df = pd.DataFrame(trows)
        for c in ['thr','roc','pr','f1','fpr','fnr']:
            ts_df[c] = ts_df[c].round(4)
        display(Markdown('### Threshold sensitivity (all rules)'))
        display(ts_df)

================================================================================
  Plots: threshold sensitivity (3 rules per config)
================================================================================
  [plot] final_plot\threshold_sensitivity.png

### Threshold sensitivity (all rules)

   dataset   ssl             mode           rule     thr     roc      pr      f1     fpr     fnr
0   gotham  byol    frozen_single     f1_optimal  0.4739  0.9991  0.9977  0.9661  0.0098  0.0420
1   gotham  byol    frozen_single       balanced  0.4739  0.9991  0.9977  0.9661  0.0098  0.0420
2   gotham  byol    frozen_single  prior_matched  0.3409  0.9991  0.9977  0.9661  0.0098  0.0420
3   gotham  byol  finetune_single     f1_optimal  0.6853  0.9999  0.9997  0.9876  0.0098  0.0000
4   gotham  byol  finetune_single       balanced  0.6853  0.9999  0.9997  0.9876  0.0098  0.0000
5   gotham  byol  finetune_single  prior_matched  0.6190  0.9999  0.9997  0.9876  0.0098  0.0000
6   gotham  byol  frozen_ensemble     f1_optimal  0.4123  0.9991  0.9975  0.9876  0.0098  0.0000
7   gotham  byol  frozen_ensemble       balanced  0.4123  0.9991  0.9975  0.9876  0.0098  0.0000
8   gotham  byol  frozen_ensemble  prior_matched  0.4807  0.9991  0.9975  0.9748  0.0098  0.0252
9   gotham  moco    frozen_single     f1_optimal  0.5167  0.9993  0.9984  0.9874  0.0066  0.0084
10  gotham  moco    frozen_single       balanced  0.5167  0.9993  0.9984  0.9874  0.0066  0.0084
11  gotham  moco    frozen_single  prior_matched  0.3197  0.9993  0.9984  0.9874  0.0066  0.0084
12  gotham  moco  finetune_single     f1_optimal  0.6136  0.9998  0.9996  0.9916  0.0033  0.0084
13  gotham  moco  finetune_single       balanced  0.6136  0.9998  0.9996  0.9916  0.0033  0.0084
14  gotham  moco  finetune_single  prior_matched  0.4036  0.9998  0.9996  0.9958  0.0033  0.0000
15  gotham  moco  frozen_ensemble     f1_optimal  0.4792  0.9997  0.9993  0.9916  0.0033  0.0084
16  gotham  moco  frozen_ensemble       balanced  0.4792  0.9997  0.9993  0.9916  0.0033  0.0084
17  gotham  moco  frozen_ensemble  prior_matched  0.3928  0.9997  0.9993  0.9916  0.0033  0.0084
18  nf_bot  byol    frozen_single     f1_optimal  0.4146  0.7513  0.8100  0.9287  0.3482  0.0000
19  nf_bot  byol    frozen_single       balanced  0.5343  0.7513  0.8100  0.2993  0.2632  0.8036
20  nf_bot  byol    frozen_single  prior_matched  0.4736  0.7513  0.8100  0.7258  0.2915  0.3571
21  nf_bot  byol  finetune_single     f1_optimal  0.3667  0.9003  0.8963  0.9302  0.3401  0.0000
22  nf_bot  byol  finetune_single       balanced  0.5437  0.9003  0.8963  0.3906  0.1012  0.7464
23  nf_bot  byol  finetune_single  prior_matched  0.5119  0.9003  0.8963  0.7338  0.1012  0.3946
24  nf_bot  byol  frozen_ensemble     f1_optimal  0.4860  0.8751  0.8833  0.7664  0.1377  0.3411
25  nf_bot  byol  frozen_ensemble       balanced  0.4876  0.8751  0.8833  0.4911  0.1336  0.6554
26  nf_bot  byol  frozen_ensemble  prior_matched  0.4865  0.8751  0.8833  0.7429  0.1377  0.3732
27  nf_bot  moco    frozen_single     f1_optimal  0.3808  0.9083  0.9259  0.8891  0.5688  0.0000
28  nf_bot  moco    frozen_single       balanced  0.4872  0.9083  0.9259  0.4279  0.0706  0.7194
29  nf_bot  moco    frozen_single  prior_matched  0.4844  0.9083  0.9259  0.8615  0.1041  0.2088
30  nf_bot  moco  finetune_single     f1_optimal  0.4930  0.8488  0.8710  0.9246  0.3320  0.0143
31  nf_bot  moco  finetune_single       balanced  0.5230  0.8488  0.8710  0.3177  0.1336  0.8000
32  nf_bot  moco  finetune_single  prior_matched  0.5160  0.8488  0.8710  0.7526  0.1619  0.3536
33  nf_bot  moco  frozen_ensemble     f1_optimal  0.4467  0.8778  0.8962  0.9280  0.3234  0.0114
34  nf_bot  moco  frozen_ensemble       balanced  0.5012  0.8778  0.8962  0.3950  0.1227  0.7406
35  nf_bot  moco  frozen_ensemble  prior_matched  0.4913  0.8778  0.8962  0.8018  0.1375  0.2904
36  nf_ton  byol    frozen_single     f1_optimal  0.3475  0.9876  0.9984  0.9757  0.0882  0.0364
37  nf_ton  byol    frozen_single       balanced  0.6359  0.9876  0.9984  0.9606  0.0065  0.0751
38  nf_ton  byol    frozen_single  prior_matched  0.3079  0.9876  0.9984  0.9767  0.1269  0.0296
39  nf_ton  byol  finetune_single     f1_optimal  0.2854  0.9837  0.9979  0.9743  0.1075  0.0367
40  nf_ton  byol  finetune_single       balanced  0.8605  0.9837  0.9979  0.9419  0.0108  0.1086
41  nf_ton  byol  finetune_single  prior_matched  0.2782  0.9837  0.9979  0.9742  0.1183  0.0355
42  nf_ton  byol  frozen_ensemble     f1_optimal  0.4035  0.9873  0.9984  0.9749  0.0839  0.0384
43  nf_ton  byol  frozen_ensemble       balanced  0.5606  0.9873  0.9984  0.9671  0.0280  0.0603
44  nf_ton  byol  frozen_ensemble  prior_matched  0.3343  0.9873  0.9984  0.9773  0.1333  0.0276
45  nf_ton  moco    frozen_single     f1_optimal  0.5170  0.9850  0.9980  0.9719  0.0645  0.0466
46  nf_ton  moco    frozen_single       balanced  0.7164  0.9850  0.9980  0.9573  0.0323  0.0779
47  nf_ton  moco    frozen_single  prior_matched  0.3837  0.9850  0.9980  0.9739  0.1419  0.0330
48  nf_ton  moco  finetune_single     f1_optimal  0.1831  0.9845  0.9980  0.9728  0.1871  0.0296
49  nf_ton  moco  finetune_single       balanced  0.7059  0.9845  0.9980  0.9473  0.0129  0.0987
50  nf_ton  moco  finetune_single  prior_matched  0.2133  0.9845  0.9980  0.9727  0.1376  0.0358
51  nf_ton  moco  frozen_ensemble     f1_optimal  0.4199  0.9880  0.9984  0.9738  0.0731  0.0418
52  nf_ton  moco  frozen_ensemble       balanced  0.6391  0.9880  0.9984  0.9662  0.0280  0.0620
53  nf_ton  moco  frozen_ensemble  prior_matched  0.3596  0.9880  0.9984  0.9764  0.1204  0.0310

In [15]:
# =====================================================================
# Cell 14 — Plot: SSL diagnostics
# =====================================================================
with safe_section('Plots: SSL diagnostics'):
    for ssl, plot_root in (('byol', DIR_SSL_BYOL), ('moco', DIR_SSL_MOCO)):
        for ds in DATASET_ORDER:
            ddir = DATASET_CONFIG[ds]
            if not os.path.isdir(ddir): continue
            rep = load_json(os.path.join(ddir, f'ssl_checkpoints_{ssl}', 'ssl_report.json'))
            if rep is None: continue
            out_dir = os.path.join(plot_root, ds); os.makedirs(out_dir, exist_ok=True)
            hist = rep.get('history', []) or []
            if not hist: continue
            ep = np.array([h.get('epoch', i+1) for i, h in enumerate(hist)], dtype=float)
            loss = np.array([h.get('train_loss', np.nan) for h in hist], dtype=float)
            fig, ax = plt.subplots(figsize=(8, 4.5))
            ax.plot(ep, loss, 'o-', label='train loss', color='#4C72B0')
            ax.set_xlabel('Epoch'); ax.set_ylabel('Loss')
            ax.set_title(f'SSL {ssl.upper()} — {ds} — training loss')
            ax.legend(); ax.grid(alpha=0.3)
            save_fig(fig, os.path.join(out_dir, f'{ssl}_losses.png'))

            for field, fname, ylab in [
                (['probe_val_roc', 'probe_test_roc'], 'probe_roc', 'ROC'),
                (['probe_test_pr'], 'probe_pr', 'PR'),
                (['probe_test_fpr'], 'probe_fpr', 'FPR'),
                (['probe_test_fnr'], 'probe_fnr', 'FNR'),
                (['probe_val_silhouette'], 'probe_silhouette', 'Silhouette'),
            ]:
                ys = []
                for h in hist:
                    v = np.nan
                    for f in field:
                        if f in h and h[f] is not None:
                            try: v = float(h[f]); break
                            except Exception: pass
                    ys.append(v)
                ys = np.array(ys, dtype=float)
                if not np.isfinite(ys).any(): continue
                fig, ax = plt.subplots(figsize=(8, 4.5))
                ax.plot(ep, ys, 'o-', color='#55A868')
                ax.set_xlabel('Epoch'); ax.set_ylabel(ylab)
                ax.set_title(f'SSL {ssl.upper()} — {ds} — {ylab}')
                ax.grid(alpha=0.3)
                save_fig(fig, os.path.join(out_dir, f'{ssl}_{fname}.png'))
            print(f'  {ds}/{ssl}: SSL diagnostics written')

================================================================================
  Plots: SSL diagnostics
================================================================================
  [plot] final_plot\ssl_plots\BYOL\gotham\byol_losses.png
  [plot] final_plot\ssl_plots\BYOL\gotham\byol_probe_roc.png
  [plot] final_plot\ssl_plots\BYOL\gotham\byol_probe_pr.png
  [plot] final_plot\ssl_plots\BYOL\gotham\byol_probe_fpr.png
  [plot] final_plot\ssl_plots\BYOL\gotham\byol_probe_fnr.png
  [plot] final_plot\ssl_plots\BYOL\gotham\byol_probe_silhouette.png
  gotham/byol: SSL diagnostics written
  [plot] final_plot\ssl_plots\BYOL\nf_bot\byol_losses.png
  [plot] final_plot\ssl_plots\BYOL\nf_bot\byol_probe_roc.png
  [plot] final_plot\ssl_plots\BYOL\nf_bot\byol_probe_pr.png
  [plot] final_plot\ssl_plots\BYOL\nf_bot\byol_probe_fpr.png
  [plot] final_plot\ssl_plots\BYOL\nf_bot\byol_probe_fnr.png
  [plot] final_plot\ssl_plots\BYOL\nf_bot\byol_probe_silhouette.png
  nf_bot/byol: SSL diagnostics written
  [plot] final_plot\ssl_plots\BYOL\nf_ton\byol_losses.png
  [plot] final_plot\ssl_plots\BYOL\nf_ton\byol_probe_roc.png
  [plot] final_plot\ssl_plots\BYOL\nf_ton\byol_probe_pr.png
  [plot] final_plot\ssl_plots\BYOL\nf_ton\byol_probe_fpr.png
  [plot] final_plot\ssl_plots\BYOL\nf_ton\byol_probe_fnr.png
  [plot] final_plot\ssl_plots\BYOL\nf_ton\byol_probe_silhouette.png
  nf_ton/byol: SSL diagnostics written
  [plot] final_plot\ssl_plots\MOCO\gotham\moco_losses.png
  [plot] final_plot\ssl_plots\MOCO\gotham\moco_probe_roc.png
  [plot] final_plot\ssl_plots\MOCO\gotham\moco_probe_pr.png
  [plot] final_plot\ssl_plots\MOCO\gotham\moco_probe_fpr.png
  [plot] final_plot\ssl_plots\MOCO\gotham\moco_probe_fnr.png
  [plot] final_plot\ssl_plots\MOCO\gotham\moco_probe_silhouette.png
  gotham/moco: SSL diagnostics written
  [plot] final_plot\ssl_plots\MOCO\nf_bot\moco_losses.png
  [plot] final_plot\ssl_plots\MOCO\nf_bot\moco_probe_roc.png
  [plot] final_plot\ssl_plots\MOCO\nf_bot\moco_probe_pr.png
  [plot] final_plot\ssl_plots\MOCO\nf_bot\moco_probe_fpr.png
  [plot] final_plot\ssl_plots\MOCO\nf_bot\moco_probe_fnr.png
  [plot] final_plot\ssl_plots\MOCO\nf_bot\moco_probe_silhouette.png
  nf_bot/moco: SSL diagnostics written
  [plot] final_plot\ssl_plots\MOCO\nf_ton\moco_losses.png
  [plot] final_plot\ssl_plots\MOCO\nf_ton\moco_probe_roc.png
  [plot] final_plot\ssl_plots\MOCO\nf_ton\moco_probe_pr.png
  [plot] final_plot\ssl_plots\MOCO\nf_ton\moco_probe_fpr.png
  [plot] final_plot\ssl_plots\MOCO\nf_ton\moco_probe_fnr.png
  [plot] final_plot\ssl_plots\MOCO\nf_ton\moco_probe_silhouette.png
  nf_ton/moco: SSL diagnostics written

In [16]:
# =====================================================================
# Cell 15 — Plot: dataset explorer (F1..F8) + split timeline + multiwindow
# =====================================================================
with safe_section('Plots: dataset explorer'):
    letters = ['a', 'b', 'c', 'd']

    # F1 class distribution
    for i, ds in enumerate(DATASET_ORDER):
        if not os.path.isdir(DATASET_CONFIG[ds]): continue
        gs = all_graphs(ds)
        if not gs: continue
        thr = max(DATASET_THRESHOLDS[ds], ATTACK_THR_DEFAULT)
        cnt = Counter(graph_label(g, thr) for g in gs)
        if not cnt: continue
        ser = pd.Series(cnt).sort_values(ascending=True)
        fig, ax = plt.subplots(figsize=(6, max(2.2, 0.35*len(ser))))
        ax.barh(ser.index, ser.values, color=sns.color_palette('rocket', len(ser)))
        ax.set_xscale('log'); ax.set_xlabel('graphs (log)'); ax.set_title(f'Class dist. — {ds}')
        save_fig(fig, os.path.join(DIR_FIGS, f'F1{letters[i]}_class_dist_{slug(ds)}.png'))

    # F2 graph stats
    for fname, col, label, logscale in [
        ('F2a_nodes_per_graph', 0, 'nodes / graph', True),
        ('F2b_edges_per_graph', 1, 'edges / graph', True),
        ('F2c_edges_per_node',  2, 'edges / node', False),
        ('F2d_components',      3, 'components', True)]:
        fig, ax = plt.subplots(figsize=(7, 4))
        any_d = False
        for ds in DATASET_ORDER:
            if not os.path.isdir(DATASET_CONFIG[ds]): continue
            st = np.array([graph_stats(g) for g in all_graphs(ds)])
            if st.size == 0: continue
            ax.hist(st[:, col], bins=40, alpha=0.5, label=ds); any_d = True
        if not any_d: plt.close(fig); continue
        if logscale: ax.set_yscale('log')
        ax.set_xlabel(label); ax.set_ylabel('count'); ax.legend(fontsize=8)
        ax.set_title(f'Distribution of {label}')
        save_fig(fig, os.path.join(DIR_FIGS, f'{fname}.png'))

    # F5 split coverage
    for i, ds in enumerate(DATASET_ORDER):
        root = DATASET_CONFIG[ds]
        if not os.path.isdir(root): continue
        tr = load_split(ds, 'train'); va = load_split(ds, 'val'); te = load_split(ds, 'test')
        if tr is None: continue
        thr = max(DATASET_THRESHOLDS[ds], ATTACK_THR_DEFAULT)
        ctr = Counter(graph_label(g, thr) for g in tr)
        cva = Counter(graph_label(g, thr) for g in va)
        cte = Counter(graph_label(g, thr) for g in te)
        classes = sorted(set(ctr) | set(cva) | set(cte))
        M = pd.DataFrame({'train': [ctr.get(c,0) for c in classes],
                          'val':   [cva.get(c,0) for c in classes],
                          'test':  [cte.get(c,0) for c in classes]}, index=classes)
        fig, ax = plt.subplots(figsize=(4.5, max(3, 0.35*len(M))))
        sns.heatmap(M, annot=True, fmt='d', cmap='YlOrRd', ax=ax)
        ax.set_title(f'Split coverage — {ds}')
        save_fig(fig, os.path.join(DIR_FIGS, f'F5{letters[i]}_splitcoverage_{slug(ds)}.png'))

    # F6a/F6b gaps
    def _gaps(gs):
        ts = sorted(g.window_start_unix for g in gs if hasattr(g, 'window_start_unix'))
        return np.diff(ts) if len(ts) >= 2 else np.array([])
    fig, ax = plt.subplots(figsize=(7, 4)); any_d = False
    for ds in DATASET_ORDER:
        if not os.path.isdir(DATASET_CONFIG[ds]): continue
        g = _gaps(all_graphs(ds))
        if g.size == 0: continue
        ax.hist(g, bins=200, range=(0,300), alpha=0.5, label=ds, log=True); any_d = True
    if any_d:
        ax.axvline(60, ls='--', c='k', lw=1, label='gap=60s')
        ax.set_xlabel('gap (s)'); ax.set_ylabel('count'); ax.legend(fontsize=8)
        save_fig(fig, os.path.join(DIR_FIGS, 'F6a_window_gaps.png'))
    else: plt.close(fig)

    fig, ax = plt.subplots(figsize=(7, 4)); any_d = False
    for ds in DATASET_ORDER:
        if not os.path.isdir(DATASET_CONFIG[ds]): continue
        g = _gaps(all_graphs(ds))
        if g.size == 0: continue
        lens, run = [], 1
        for d in g:
            if d <= 60: run += 1
            else: lens.append(run); run = 1
        lens.append(run)
        ax.hist(lens, bins=60, alpha=0.5, label=ds, log=True); any_d = True
    if any_d:
        ax.axvline(10, ls='--', c='k', lw=1, label='N=10')
        ax.set_xlabel('run length'); ax.set_ylabel('count'); ax.legend(fontsize=8)
        save_fig(fig, os.path.join(DIR_FIGS, 'F6b_consecutive_runs.png'))
    else: plt.close(fig)
print(f'\n  saved {_saved["ok"]} plots so far, {_saved["fail"]} failures')

================================================================================
  Plots: dataset explorer
================================================================================
  [plot] final_plot\figures\F1a_class_dist_gotham.png
  [plot] final_plot\figures\F1b_class_dist_nf_bot.png
  [plot] final_plot\figures\F1c_class_dist_nf_ton.png
  [plot] final_plot\figures\F2a_nodes_per_graph.png
  [plot] final_plot\figures\F2b_edges_per_graph.png
  [plot] final_plot\figures\F2c_edges_per_node.png
  [plot] final_plot\figures\F2d_components.png
  [plot] final_plot\figures\F5a_splitcoverage_gotham.png
  [plot] final_plot\figures\F5b_splitcoverage_nf_bot.png
  [plot] final_plot\figures\F5c_splitcoverage_nf_ton.png
  [plot] final_plot\figures\F6a_window_gaps.png
  [plot] final_plot\figures\F6b_consecutive_runs.png

  saved 250 plots so far, 0 failures

In [17]:
# =====================================================================
# Cell 16 — Plot: split timeline (7 figs per dataset)
# =====================================================================
with safe_section('Plots: split timelines'):
    GAP_THRESHOLD_H = 2.0
    SMOOTH_WINDOW_H = 20
    SPLIT_COLORS = {'train': '#4C72B0', 'val': '#55A868', 'test': '#C44E52'}

    def _smooth(y, w):
        if w <= 1: return y
        out = np.full_like(y, np.nan); half = w // 2
        for i in range(len(y)):
            lo = max(0, i-half); hi = min(len(y), i+half+1)
            m = np.isfinite(y[lo:hi])
            if m.any(): out[i] = y[lo:hi][m].mean()
        return out

    def _plot_split(ds, gdir, block_size_sec=3600, purge_sec=60,
                     attack_thr=ATTACK_THR_DEFAULT,
                     gap_h=GAP_THRESHOLD_H, smooth_h=SMOOTH_WINDOW_H):
        tr = load_pickle(os.path.join(gdir, 'train_graphs.pkl'))
        va = load_pickle(os.path.join(gdir, 'val_graphs.pkl'))
        te = load_pickle(os.path.join(gdir, 'test_graphs.pkl'))
        if tr is None or va is None or te is None: return
        def _t(gs): return np.array([float(getattr(g,'window_start_unix',0.0)) for g in gs])
        t_tr, t_va, t_te = _t(tr), _t(va), _t(te)
        all_t = np.concatenate([t_tr, t_va, t_te])
        ts_sorted = np.sort(all_t)
        gap_thr = gap_h * 3600
        comp_map = np.zeros(len(ts_sorted)); gap_c = []
        for i in range(1, len(ts_sorted)):
            d = ts_sorted[i] - ts_sorted[i-1]
            if d > gap_thr:
                comp_map[i] = comp_map[i-1] + gap_thr
                gap_c.append((comp_map[i-1] + gap_thr/2) / 3600.0)
            else:
                comp_map[i] = comp_map[i-1] + d
        def _cmp(t): return comp_map[np.searchsorted(ts_sorted, t)] / 3600.0
        c_tr, c_va, c_te = _cmp(t_tr), _cmp(t_va), _cmp(t_te)
        total_h = comp_map[-1] / 3600.0
        span_h = (all_t.max() - all_t.min()) / 3600.0
        ratio = total_h / max(span_h, 1e-9)
        af_tr = np.array([attack_frac(g) for g in tr])
        af_va = np.array([attack_frac(g) for g in va])
        af_te = np.array([attack_frac(g) for g in te])
        cl_tr = np.array([graph_label(g, attack_thr) for g in tr])
        cl_va = np.array([graph_label(g, attack_thr) for g in va])
        cl_te = np.array([graph_label(g, attack_thr) for g in te])

        # --- 01 block heatmap ---
        bh = block_size_sec / 3600.0
        nb = int(np.ceil(total_h / bh)) + 1
        def _bid(c): return np.clip((c // bh).astype(int), 0, nb-1)
        btr, bva, bte = _bid(c_tr), _bid(c_va), _bid(c_te)
        ctr_ = np.bincount(btr, minlength=nb)
        cva_ = np.bincount(bva, minlength=nb)
        cte_ = np.bincount(bte, minlength=nb)
        fig, ax = plt.subplots(figsize=(max(9, nb*0.055), 2.4))
        grid = np.vstack([ctr_, cva_, cte_]).astype(float)
        im = ax.imshow(grid, aspect='auto', cmap='Blues',
                       interpolation='nearest', vmin=0)
        ax.set_yticks([0,1,2]); ax.set_yticklabels(['train','val','test'])
        ti = np.linspace(0, nb-1, num=min(12, nb), dtype=int)
        ax.set_xticks(ti)
        ax.set_xticklabels([f'{i*bh:.0f}' for i in ti], fontsize=8)
        ax.set_xlabel('compressed time (h)')
        ax.set_title(f'{ds} — graphs per {bh:.0f}h block '
                     f'[{span_h:.0f}h → {total_h:.0f}h, {ratio:.2f}x]')
        plt.colorbar(im, ax=ax, fraction=0.025)
        save_fig(fig, os.path.join(DIR_SPLIT, f'{ds}_01_block_counts.png'))

        # --- 02 window zoom (densest 1h) ---
        all_c = np.concatenate([c_tr, c_va, c_te]); all_cs = np.sort(all_c)
        win_h = 1.0; best_lo, best_count = 0.0, 0
        for i, c0 in enumerate(all_cs):
            c1 = c0 + win_h
            cnt = int(np.searchsorted(all_cs, c1) - i)
            if cnt > best_count: best_count, best_lo = cnt, c0
        best_hi = best_lo + win_h
        rows = []
        for c_a, af, tag in [(c_tr,af_tr,'train'),(c_va,af_va,'val'),(c_te,af_te,'test')]:
            for i, c in enumerate(c_a):
                if best_lo <= c < best_hi:
                    rows.append({'c': float(c), 'split': tag, 'af': float(af[i])})
        rows.sort(key=lambda r: r['c'])
        fig, ax = plt.subplots(figsize=(11, 2.6))
        if rows:
            for r in rows:
                xi = (r['c'] - best_lo) * 3600.0 / WINDOW_SEC
                alpha = 0.25 + 0.75 * r['af']
                ax.bar(xi, 1.0, width=0.85, color=SPLIT_COLORS[r['split']],
                       alpha=alpha, edgecolor='k', linewidth=0.15)
            ax.set_xlim(0, block_size_sec / WINDOW_SEC)
            ax.set_ylim(0, 1.0); ax.set_yticks([])
            ax.set_xlabel(f'window index in block (1 = {WINDOW_SEC}s)')
            n_tr = sum(1 for r in rows if r['split'] == 'train')
            n_va = sum(1 for r in rows if r['split'] == 'val')
            n_te = sum(1 for r in rows if r['split'] == 'test')
            ax.set_title(f'{ds} — zoom on densest 1h segment '
                         f'({n_tr} train / {n_va} val / {n_te} test)')
            handles = [mpatches.Patch(color=SPLIT_COLORS[s], label=s)
                       for s in ('train','val','test')]
            ax.legend(handles=handles, loc='upper left',
                      bbox_to_anchor=(1.01, 1.0), borderaxespad=0, frameon=False)
        else:
            ax.text(0.5, 0.5, 'no graphs in zoom window',
                    ha='center', va='center', transform=ax.transAxes)
        save_fig(fig, os.path.join(DIR_SPLIT, f'{ds}_02_window_zoom.png'))

        # --- 03 attack fraction scatter ---
        fig, ax = plt.subplots(figsize=(11, 3.0))
        for c_a, af, tag in [(c_tr,af_tr,'train'),(c_va,af_va,'val'),(c_te,af_te,'test')]:
            ax.scatter(c_a, af, s=7, c=SPLIT_COLORS[tag], alpha=0.6,
                       label=tag, edgecolors='none')
        for gc_ in gap_c:
            ax.axvline(gc_, color='gray', ls='--', lw=0.6, alpha=0.6)
        ax.set_ylim(-0.02, 1.02); ax.set_xlim(0, total_h)
        ax.set_xlabel('compressed time (h)')
        ax.set_ylabel('attack-edge fraction per window')
        ax.set_title(f'{ds} — attack fraction per {WINDOW_SEC}s window')
        ax.grid(alpha=0.2); ax.legend(fontsize=8)
        save_fig(fig, os.path.join(DIR_SPLIT, f'{ds}_03_attack_fraction.png'))

        # --- 04 class presence ---
        all_classes = sorted(set(cl_tr.tolist()) | set(cl_va.tolist()) | set(cl_te.tolist()))
        all_classes = [c for c in all_classes if c != 'Benign']
        fig, ax = plt.subplots(figsize=(11, max(2.4, 0.32 * max(len(all_classes), 1))))
        if all_classes:
            cls_y = {c: i for i, c in enumerate(all_classes)}
            for c_a, cl, tag in [(c_tr, cl_tr, 'train'), (c_va, cl_va, 'val'),
                                  (c_te, cl_te, 'test')]:
                ys = np.array([cls_y.get(c, -1) for c in cl])
                m = ys >= 0
                ax.scatter(c_a[m], ys[m], s=11, c=SPLIT_COLORS[tag],
                           alpha=0.55, edgecolors='none')
            for gc_ in gap_c:
                ax.axvline(gc_, color='gray', ls='--', lw=0.6, alpha=0.6)
            ax.set_yticks(np.arange(len(all_classes)))
            ax.set_yticklabels(all_classes, fontsize=8)
            ax.set_xlim(0, total_h); ax.set_xlabel('compressed time (h)')
            ax.set_title(f'{ds} — attack class presence over time')
            ax.grid(alpha=0.2, axis='x')
            handles = [mpatches.Patch(color=SPLIT_COLORS[s], label=s)
                       for s in ('train','val','test')]
            ax.legend(handles=handles, loc='upper left',
                      bbox_to_anchor=(1.01, 1.0), borderaxespad=0, frameon=False)
        else:
            ax.text(0.5, 0.5, 'no attack classes', ha='center',
                    va='center', transform=ax.transAxes)
        save_fig(fig, os.path.join(DIR_SPLIT, f'{ds}_04_class_presence.png'))

        # --- 05 hourly count lines ---
        bins = np.arange(0, total_h + 1, 1.0)
        h_tr, _ = np.histogram(c_tr, bins=bins)
        h_va, _ = np.histogram(c_va, bins=bins)
        h_te, _ = np.histogram(c_te, bins=bins)
        x = bins[:-1] + 0.5
        fig, ax = plt.subplots(figsize=(11, 3.2))
        ax.plot(x, h_tr, '-', color=SPLIT_COLORS['train'], lw=1.6, label='train')
        ax.plot(x, h_va, '-', color=SPLIT_COLORS['val'],   lw=1.4, label='val')
        ax.plot(x, h_te, '-', color=SPLIT_COLORS['test'],  lw=1.4, label='test')
        ax.set_xlim(0, total_h); ax.set_ylim(bottom=0)
        ax.set_xlabel('compressed time (h)'); ax.set_ylabel('# graphs / hour')
        ax.set_title(f'{ds} — hourly graph count')
        ax.legend(fontsize=8); ax.grid(alpha=.3)
        save_fig(fig, os.path.join(DIR_SPLIT, f'{ds}_05_line_counts.png'))

        # --- 06 smoothed attack fraction lines ---
        def _agg(c, af, bins):
            S = np.zeros(len(bins)-1); C = np.zeros(len(bins)-1)
            for ci, ai in zip(c, af):
                j = min(int(ci), len(S)-1); S[j] += ai; C[j] += 1
            with np.errstate(invalid='ignore', divide='ignore'):
                return np.where(C > 0, S/C, np.nan)
        y_tr = _agg(c_tr, af_tr, bins)
        y_va = _agg(c_va, af_va, bins)
        y_te = _agg(c_te, af_te, bins)
        w = int(max(1, smooth_h))
        fig, ax = plt.subplots(figsize=(11, 3.2))
        ax.plot(x, _smooth(y_tr, w), '-', color=SPLIT_COLORS['train'], lw=1.6, label='train')
        ax.plot(x, _smooth(y_va, w), '-', color=SPLIT_COLORS['val'],   lw=1.4, label='val')
        ax.plot(x, _smooth(y_te, w), '-', color=SPLIT_COLORS['test'],  lw=1.4, label='test')
        ax.set_xlim(0, total_h); ax.set_ylim(-0.02, 1.02)
        ax.set_xlabel('compressed time (h)')
        ax.set_ylabel('attack fraction (smoothed)')
        ax.set_title(f'{ds} — attack fraction over time (window={w}h)')
        ax.legend(fontsize=8); ax.grid(alpha=.3)
        save_fig(fig, os.path.join(DIR_SPLIT, f'{ds}_06_line_attack_fraction.png'))

        # --- 07 cumulative count ---
        fig, ax = plt.subplots(figsize=(11, 3.2))
        for c_a, tag in [(c_tr,'train'),(c_va,'val'),(c_te,'test')]:
            cs = np.sort(c_a); ys = np.arange(1, len(cs)+1)
            ax.plot(cs, ys, '-', color=SPLIT_COLORS[tag], lw=1.6, label=tag)
        ax.set_xlim(0, total_h); ax.set_ylim(bottom=0)
        ax.set_xlabel('compressed time (h)'); ax.set_ylabel('cumulative # graphs')
        ax.set_title(f'{ds} — cumulative graph count')
        ax.legend(fontsize=8); ax.grid(alpha=.3)
        save_fig(fig, os.path.join(DIR_SPLIT, f'{ds}_07_line_cumulative.png'))

    for ds in DATASET_ORDER:
        d = DATASET_CONFIG[ds]
        if not os.path.isdir(d): continue
        ns = load_json(os.path.join(d, 'norm_stats.json')) or {}
        bs = int(ns.get('block_size_sec', 3600))
        pg = int(ns.get('purge_sec', 60))
        try:
            _plot_split(ds, d, block_size_sec=bs, purge_sec=pg)
        except Exception as e:
            import traceback; traceback.print_exc()
            print(f'  [FAIL] split plots {ds}: {e}')

================================================================================
  Plots: split timelines
================================================================================
  [plot] final_plot\split_plots\gotham_01_block_counts.png
  [plot] final_plot\split_plots\gotham_02_window_zoom.png
  [plot] final_plot\split_plots\gotham_03_attack_fraction.png
  [plot] final_plot\split_plots\gotham_04_class_presence.png
  [plot] final_plot\split_plots\gotham_05_line_counts.png
  [plot] final_plot\split_plots\gotham_06_line_attack_fraction.png
  [plot] final_plot\split_plots\gotham_07_line_cumulative.png
  [plot] final_plot\split_plots\nf_bot_01_block_counts.png
  [plot] final_plot\split_plots\nf_bot_02_window_zoom.png
  [plot] final_plot\split_plots\nf_bot_03_attack_fraction.png
  [plot] final_plot\split_plots\nf_bot_04_class_presence.png
  [plot] final_plot\split_plots\nf_bot_05_line_counts.png
  [plot] final_plot\split_plots\nf_bot_06_line_attack_fraction.png
  [plot] final_plot\split_plots\nf_bot_07_line_cumulative.png
  [plot] final_plot\split_plots\nf_ton_01_block_counts.png
  [plot] final_plot\split_plots\nf_ton_02_window_zoom.png
  [plot] final_plot\split_plots\nf_ton_03_attack_fraction.png
  [plot] final_plot\split_plots\nf_ton_04_class_presence.png
  [plot] final_plot\split_plots\nf_ton_05_line_counts.png
  [plot] final_plot\split_plots\nf_ton_06_line_attack_fraction.png
  [plot] final_plot\split_plots\nf_ton_07_line_cumulative.png

In [18]:
# =====================================================================
# Cell 17 — Save DB again + summary
# =====================================================================
DB['meta']['last_updated_utc'] = datetime.datetime.utcnow().isoformat() + 'Z'
save_json(MASTER_DB, DB)

with safe_section('Final summary'):
    totals = defaultdict(lambda: [0, 0.0])
    for dp, _, fns in os.walk(FINAL_ROOT):
        rel = os.path.relpath(dp, FINAL_ROOT)
        top = rel.split(os.sep)[0] if rel != '.' else '(root)'
        for fn in fns:
            if fn.lower().endswith(('.png','.pdf','.svg','.jpg')):
                totals[top][0] += 1
                totals[top][1] += os.path.getsize(os.path.join(dp, fn)) / 1024
    print(f"\n{'='*72}\n  FINAL PLOT SUMMARY — {_saved['ok']} ok / {_saved['fail']} fail\n{'='*72}")
    g_n, g_mb = 0, 0.0
    for k in sorted(totals):
        n, kb = totals[k]; g_n += n; g_mb += kb/1024
        print(f'  {k:<24} {n:>4} files  {kb/1024:>6.1f} MB')
    print(f'  {"-"*50}\n  {"TOTAL":<24} {g_n:>4} files  {g_mb:>6.1f} MB')
    print(f'\n  DB: {MASTER_DB}')
    print(f'  Plots root: {os.path.abspath(FINAL_ROOT)}/')

================================================================================
  Final summary
================================================================================

========================================================================
  FINAL PLOT SUMMARY — 271 ok / 0 fail
========================================================================
  (root)                      1 files     0.1 MB
  baseline_plots            122 files     8.3 MB
  figures                    34 files     1.5 MB
  phase3_plots               73 files     2.3 MB
  phase3_plots_moco          73 files     2.3 MB
  split_plots                21 files     1.4 MB
  ssl_plots                  48 files     1.9 MB
  --------------------------------------------------
  TOTAL                     372 files    17.7 MB

  DB: master_db.json
  Plots root: c:\Users\User\Desktop\MC-STGAT-IDS Experiment\MC-STGAT-IDS-V5\final_plot/